/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ActiveOrganizationRepresentation.Builder.class)
public final class ActiveOrganizationRepresentation {
    private final Optional<String> organizationId;

    private final Optional<String> organizationName;

    private final Optional<String> displayName;

    private final Optional<List<String>> roles;

    private final Optional<OffsetDateTime> switchedAt;

    private final Map<String, Object> additionalProperties;

    private ActiveOrganizationRepresentation(
            Optional<String> organizationId,
            Optional<String> organizationName,
            Optional<String> displayName,
            Optional<List<String>> roles,
            Optional<OffsetDateTime> switchedAt,
            Map<String, Object> additionalProperties) {
        this.organizationId = organizationId;
        this.organizationName = organizationName;
        this.displayName = displayName;
        this.roles = roles;
        this.switchedAt = switchedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the active organization
     */
    @JsonProperty("organizationId")
    public Optional<String> getOrganizationId() {
        return organizationId;
    }

    /**
     * @return The name of the active organization
     */
    @JsonProperty("organizationName")
    public Optional<String> getOrganizationName() {
        return organizationName;
    }

    /**
     * @return The display name of the active organization
     */
    @JsonProperty("displayName")
    public Optional<String> getDisplayName() {
        return displayName;
    }

    /**
     * @return User's roles in the active organization
     */
    @JsonProperty("roles")
    public Optional<List<String>> getRoles() {
        return roles;
    }

    /**
     * @return When the organization was last switched to
     */
    @JsonProperty("switchedAt")
    public Optional<OffsetDateTime> getSwitchedAt() {
        return switchedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActiveOrganizationRepresentation && equalTo((ActiveOrganizationRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ActiveOrganizationRepresentation other) {
        return organizationId.equals(other.organizationId)
                && organizationName.equals(other.organizationName)
                && displayName.equals(other.displayName)
                && roles.equals(other.roles)
                && switchedAt.equals(other.switchedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizationId, this.organizationName, this.displayName, this.roles, this.switchedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> organizationId = Optional.empty();

        private Optional<String> organizationName = Optional.empty();

        private Optional<String> displayName = Optional.empty();

        private Optional<List<String>> roles = Optional.empty();

        private Optional<OffsetDateTime> switchedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ActiveOrganizationRepresentation other) {
            organizationId(other.getOrganizationId());
            organizationName(other.getOrganizationName());
            displayName(other.getDisplayName());
            roles(other.getRoles());
            switchedAt(other.getSwitchedAt());
            return this;
        }

        @JsonSetter(value = "organizationId", nulls = Nulls.SKIP)
        public Builder organizationId(Optional<String> organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        public Builder organizationId(String organizationId) {
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        @JsonSetter(value = "organizationName", nulls = Nulls.SKIP)
        public Builder organizationName(Optional<String> organizationName) {
            this.organizationName = organizationName;
            return this;
        }

        public Builder organizationName(String organizationName) {
            this.organizationName = Optional.ofNullable(organizationName);
            return this;
        }

        @JsonSetter(value = "displayName", nulls = Nulls.SKIP)
        public Builder displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        @JsonSetter(value = "roles", nulls = Nulls.SKIP)
        public Builder roles(Optional<List<String>> roles) {
            this.roles = roles;
            return this;
        }

        public Builder roles(List<String> roles) {
            this.roles = Optional.ofNullable(roles);
            return this;
        }

        @JsonSetter(value = "switchedAt", nulls = Nulls.SKIP)
        public Builder switchedAt(Optional<OffsetDateTime> switchedAt) {
            this.switchedAt = switchedAt;
            return this;
        }

        public Builder switchedAt(OffsetDateTime switchedAt) {
            this.switchedAt = Optional.ofNullable(switchedAt);
            return this;
        }

        public ActiveOrganizationRepresentation build() {
            return new ActiveOrganizationRepresentation(
                    organizationId, organizationName, displayName, roles, switchedAt, additionalProperties);
        }
    }
}
