/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CredentialRepresentation.Builder.class)
public final class CredentialRepresentation {
    private final Optional<String> id;

    private final Optional<String> type;

    private final Optional<String> userLabel;

    private final Optional<Long> createdDate;

    private final Optional<String> secretData;

    private final Optional<String> credentialData;

    private final Optional<Integer> priority;

    private final Optional<String> value;

    private final Optional<Boolean> temporary;

    private final Optional<String> device;

    private final Optional<String> hashedSaltedValue;

    private final Optional<String> salt;

    private final Optional<Integer> hashIterations;

    private final Optional<Integer> counter;

    private final Optional<String> algorithm;

    private final Optional<Integer> digits;

    private final Optional<Integer> period;

    private final Optional<Map<String, List<String>>> config;

    private final Optional<String> federationLink;

    private final Map<String, Object> additionalProperties;

    private CredentialRepresentation(
            Optional<String> id,
            Optional<String> type,
            Optional<String> userLabel,
            Optional<Long> createdDate,
            Optional<String> secretData,
            Optional<String> credentialData,
            Optional<Integer> priority,
            Optional<String> value,
            Optional<Boolean> temporary,
            Optional<String> device,
            Optional<String> hashedSaltedValue,
            Optional<String> salt,
            Optional<Integer> hashIterations,
            Optional<Integer> counter,
            Optional<String> algorithm,
            Optional<Integer> digits,
            Optional<Integer> period,
            Optional<Map<String, List<String>>> config,
            Optional<String> federationLink,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.type = type;
        this.userLabel = userLabel;
        this.createdDate = createdDate;
        this.secretData = secretData;
        this.credentialData = credentialData;
        this.priority = priority;
        this.value = value;
        this.temporary = temporary;
        this.device = device;
        this.hashedSaltedValue = hashedSaltedValue;
        this.salt = salt;
        this.hashIterations = hashIterations;
        this.counter = counter;
        this.algorithm = algorithm;
        this.digits = digits;
        this.period = period;
        this.config = config;
        this.federationLink = federationLink;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    @JsonProperty("userLabel")
    public Optional<String> getUserLabel() {
        return userLabel;
    }

    @JsonProperty("createdDate")
    public Optional<Long> getCreatedDate() {
        return createdDate;
    }

    @JsonProperty("secretData")
    public Optional<String> getSecretData() {
        return secretData;
    }

    @JsonProperty("credentialData")
    public Optional<String> getCredentialData() {
        return credentialData;
    }

    @JsonProperty("priority")
    public Optional<Integer> getPriority() {
        return priority;
    }

    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @JsonProperty("temporary")
    public Optional<Boolean> getTemporary() {
        return temporary;
    }

    @JsonProperty("device")
    public Optional<String> getDevice() {
        return device;
    }

    @JsonProperty("hashedSaltedValue")
    public Optional<String> getHashedSaltedValue() {
        return hashedSaltedValue;
    }

    @JsonProperty("salt")
    public Optional<String> getSalt() {
        return salt;
    }

    @JsonProperty("hashIterations")
    public Optional<Integer> getHashIterations() {
        return hashIterations;
    }

    @JsonProperty("counter")
    public Optional<Integer> getCounter() {
        return counter;
    }

    @JsonProperty("algorithm")
    public Optional<String> getAlgorithm() {
        return algorithm;
    }

    @JsonProperty("digits")
    public Optional<Integer> getDigits() {
        return digits;
    }

    @JsonProperty("period")
    public Optional<Integer> getPeriod() {
        return period;
    }

    @JsonProperty("config")
    public Optional<Map<String, List<String>>> getConfig() {
        return config;
    }

    @JsonProperty("federationLink")
    public Optional<String> getFederationLink() {
        return federationLink;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CredentialRepresentation && equalTo((CredentialRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CredentialRepresentation other) {
        return id.equals(other.id)
                && type.equals(other.type)
                && userLabel.equals(other.userLabel)
                && createdDate.equals(other.createdDate)
                && secretData.equals(other.secretData)
                && credentialData.equals(other.credentialData)
                && priority.equals(other.priority)
                && value.equals(other.value)
                && temporary.equals(other.temporary)
                && device.equals(other.device)
                && hashedSaltedValue.equals(other.hashedSaltedValue)
                && salt.equals(other.salt)
                && hashIterations.equals(other.hashIterations)
                && counter.equals(other.counter)
                && algorithm.equals(other.algorithm)
                && digits.equals(other.digits)
                && period.equals(other.period)
                && config.equals(other.config)
                && federationLink.equals(other.federationLink);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.type,
                this.userLabel,
                this.createdDate,
                this.secretData,
                this.credentialData,
                this.priority,
                this.value,
                this.temporary,
                this.device,
                this.hashedSaltedValue,
                this.salt,
                this.hashIterations,
                this.counter,
                this.algorithm,
                this.digits,
                this.period,
                this.config,
                this.federationLink);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Optional<String> userLabel = Optional.empty();

        private Optional<Long> createdDate = Optional.empty();

        private Optional<String> secretData = Optional.empty();

        private Optional<String> credentialData = Optional.empty();

        private Optional<Integer> priority = Optional.empty();

        private Optional<String> value = Optional.empty();

        private Optional<Boolean> temporary = Optional.empty();

        private Optional<String> device = Optional.empty();

        private Optional<String> hashedSaltedValue = Optional.empty();

        private Optional<String> salt = Optional.empty();

        private Optional<Integer> hashIterations = Optional.empty();

        private Optional<Integer> counter = Optional.empty();

        private Optional<String> algorithm = Optional.empty();

        private Optional<Integer> digits = Optional.empty();

        private Optional<Integer> period = Optional.empty();

        private Optional<Map<String, List<String>>> config = Optional.empty();

        private Optional<String> federationLink = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CredentialRepresentation other) {
            id(other.getId());
            type(other.getType());
            userLabel(other.getUserLabel());
            createdDate(other.getCreatedDate());
            secretData(other.getSecretData());
            credentialData(other.getCredentialData());
            priority(other.getPriority());
            value(other.getValue());
            temporary(other.getTemporary());
            device(other.getDevice());
            hashedSaltedValue(other.getHashedSaltedValue());
            salt(other.getSalt());
            hashIterations(other.getHashIterations());
            counter(other.getCounter());
            algorithm(other.getAlgorithm());
            digits(other.getDigits());
            period(other.getPeriod());
            config(other.getConfig());
            federationLink(other.getFederationLink());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        @JsonSetter(value = "userLabel", nulls = Nulls.SKIP)
        public Builder userLabel(Optional<String> userLabel) {
            this.userLabel = userLabel;
            return this;
        }

        public Builder userLabel(String userLabel) {
            this.userLabel = Optional.ofNullable(userLabel);
            return this;
        }

        @JsonSetter(value = "createdDate", nulls = Nulls.SKIP)
        public Builder createdDate(Optional<Long> createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        public Builder createdDate(Long createdDate) {
            this.createdDate = Optional.ofNullable(createdDate);
            return this;
        }

        @JsonSetter(value = "secretData", nulls = Nulls.SKIP)
        public Builder secretData(Optional<String> secretData) {
            this.secretData = secretData;
            return this;
        }

        public Builder secretData(String secretData) {
            this.secretData = Optional.ofNullable(secretData);
            return this;
        }

        @JsonSetter(value = "credentialData", nulls = Nulls.SKIP)
        public Builder credentialData(Optional<String> credentialData) {
            this.credentialData = credentialData;
            return this;
        }

        public Builder credentialData(String credentialData) {
            this.credentialData = Optional.ofNullable(credentialData);
            return this;
        }

        @JsonSetter(value = "priority", nulls = Nulls.SKIP)
        public Builder priority(Optional<Integer> priority) {
            this.priority = priority;
            return this;
        }

        public Builder priority(Integer priority) {
            this.priority = Optional.ofNullable(priority);
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @JsonSetter(value = "temporary", nulls = Nulls.SKIP)
        public Builder temporary(Optional<Boolean> temporary) {
            this.temporary = temporary;
            return this;
        }

        public Builder temporary(Boolean temporary) {
            this.temporary = Optional.ofNullable(temporary);
            return this;
        }

        @JsonSetter(value = "device", nulls = Nulls.SKIP)
        public Builder device(Optional<String> device) {
            this.device = device;
            return this;
        }

        public Builder device(String device) {
            this.device = Optional.ofNullable(device);
            return this;
        }

        @JsonSetter(value = "hashedSaltedValue", nulls = Nulls.SKIP)
        public Builder hashedSaltedValue(Optional<String> hashedSaltedValue) {
            this.hashedSaltedValue = hashedSaltedValue;
            return this;
        }

        public Builder hashedSaltedValue(String hashedSaltedValue) {
            this.hashedSaltedValue = Optional.ofNullable(hashedSaltedValue);
            return this;
        }

        @JsonSetter(value = "salt", nulls = Nulls.SKIP)
        public Builder salt(Optional<String> salt) {
            this.salt = salt;
            return this;
        }

        public Builder salt(String salt) {
            this.salt = Optional.ofNullable(salt);
            return this;
        }

        @JsonSetter(value = "hashIterations", nulls = Nulls.SKIP)
        public Builder hashIterations(Optional<Integer> hashIterations) {
            this.hashIterations = hashIterations;
            return this;
        }

        public Builder hashIterations(Integer hashIterations) {
            this.hashIterations = Optional.ofNullable(hashIterations);
            return this;
        }

        @JsonSetter(value = "counter", nulls = Nulls.SKIP)
        public Builder counter(Optional<Integer> counter) {
            this.counter = counter;
            return this;
        }

        public Builder counter(Integer counter) {
            this.counter = Optional.ofNullable(counter);
            return this;
        }

        @JsonSetter(value = "algorithm", nulls = Nulls.SKIP)
        public Builder algorithm(Optional<String> algorithm) {
            this.algorithm = algorithm;
            return this;
        }

        public Builder algorithm(String algorithm) {
            this.algorithm = Optional.ofNullable(algorithm);
            return this;
        }

        @JsonSetter(value = "digits", nulls = Nulls.SKIP)
        public Builder digits(Optional<Integer> digits) {
            this.digits = digits;
            return this;
        }

        public Builder digits(Integer digits) {
            this.digits = Optional.ofNullable(digits);
            return this;
        }

        @JsonSetter(value = "period", nulls = Nulls.SKIP)
        public Builder period(Optional<Integer> period) {
            this.period = period;
            return this;
        }

        public Builder period(Integer period) {
            this.period = Optional.ofNullable(period);
            return this;
        }

        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public Builder config(Optional<Map<String, List<String>>> config) {
            this.config = config;
            return this;
        }

        public Builder config(Map<String, List<String>> config) {
            this.config = Optional.ofNullable(config);
            return this;
        }

        @JsonSetter(value = "federationLink", nulls = Nulls.SKIP)
        public Builder federationLink(Optional<String> federationLink) {
            this.federationLink = federationLink;
            return this;
        }

        public Builder federationLink(String federationLink) {
            this.federationLink = Optional.ofNullable(federationLink);
            return this;
        }

        public CredentialRepresentation build() {
            return new CredentialRepresentation(
                    id,
                    type,
                    userLabel,
                    createdDate,
                    secretData,
                    credentialData,
                    priority,
                    value,
                    temporary,
                    device,
                    hashedSaltedValue,
                    salt,
                    hashIterations,
                    counter,
                    algorithm,
                    digits,
                    period,
                    config,
                    federationLink,
                    additionalProperties);
        }
    }
}
