/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetOrganizationMembershipsRequest.Builder.class)
public final class GetOrganizationMembershipsRequest {
    private final Optional<String> search;

    private final Optional<Integer> first;

    private final Optional<Integer> max;

    private final Optional<Boolean> excludeAdminAccounts;

    private final Optional<Boolean> includeOrgs;

    private final Map<String, Object> additionalProperties;

    private GetOrganizationMembershipsRequest(
            Optional<String> search,
            Optional<Integer> first,
            Optional<Integer> max,
            Optional<Boolean> excludeAdminAccounts,
            Optional<Boolean> includeOrgs,
            Map<String, Object> additionalProperties) {
        this.search = search;
        this.first = first;
        this.max = max;
        this.excludeAdminAccounts = excludeAdminAccounts;
        this.includeOrgs = includeOrgs;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("search")
    public Optional<String> getSearch() {
        return search;
    }

    @JsonProperty("first")
    public Optional<Integer> getFirst() {
        return first;
    }

    @JsonProperty("max")
    public Optional<Integer> getMax() {
        return max;
    }

    @JsonProperty("excludeAdminAccounts")
    public Optional<Boolean> getExcludeAdminAccounts() {
        return excludeAdminAccounts;
    }

    @JsonProperty("includeOrgs")
    public Optional<Boolean> getIncludeOrgs() {
        return includeOrgs;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetOrganizationMembershipsRequest && equalTo((GetOrganizationMembershipsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetOrganizationMembershipsRequest other) {
        return search.equals(other.search)
                && first.equals(other.first)
                && max.equals(other.max)
                && excludeAdminAccounts.equals(other.excludeAdminAccounts)
                && includeOrgs.equals(other.includeOrgs);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.search, this.first, this.max, this.excludeAdminAccounts, this.includeOrgs);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> search = Optional.empty();

        private Optional<Integer> first = Optional.empty();

        private Optional<Integer> max = Optional.empty();

        private Optional<Boolean> excludeAdminAccounts = Optional.empty();

        private Optional<Boolean> includeOrgs = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetOrganizationMembershipsRequest other) {
            search(other.getSearch());
            first(other.getFirst());
            max(other.getMax());
            excludeAdminAccounts(other.getExcludeAdminAccounts());
            includeOrgs(other.getIncludeOrgs());
            return this;
        }

        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(Optional<String> search) {
            this.search = search;
            return this;
        }

        public Builder search(String search) {
            this.search = Optional.ofNullable(search);
            return this;
        }

        @JsonSetter(value = "first", nulls = Nulls.SKIP)
        public Builder first(Optional<Integer> first) {
            this.first = first;
            return this;
        }

        public Builder first(Integer first) {
            this.first = Optional.ofNullable(first);
            return this;
        }

        @JsonSetter(value = "max", nulls = Nulls.SKIP)
        public Builder max(Optional<Integer> max) {
            this.max = max;
            return this;
        }

        public Builder max(Integer max) {
            this.max = Optional.ofNullable(max);
            return this;
        }

        @JsonSetter(value = "excludeAdminAccounts", nulls = Nulls.SKIP)
        public Builder excludeAdminAccounts(Optional<Boolean> excludeAdminAccounts) {
            this.excludeAdminAccounts = excludeAdminAccounts;
            return this;
        }

        public Builder excludeAdminAccounts(Boolean excludeAdminAccounts) {
            this.excludeAdminAccounts = Optional.ofNullable(excludeAdminAccounts);
            return this;
        }

        @JsonSetter(value = "includeOrgs", nulls = Nulls.SKIP)
        public Builder includeOrgs(Optional<Boolean> includeOrgs) {
            this.includeOrgs = includeOrgs;
            return this;
        }

        public Builder includeOrgs(Boolean includeOrgs) {
            this.includeOrgs = Optional.ofNullable(includeOrgs);
            return this;
        }

        public GetOrganizationMembershipsRequest build() {
            return new GetOrganizationMembershipsRequest(
                    search, first, max, excludeAdminAccounts, includeOrgs, additionalProperties);
        }
    }
}
