/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetOrganizationInvitationsRequest.Builder.class)
public final class GetOrganizationInvitationsRequest {
    private final Optional<String> search;

    private final Optional<Integer> first;

    private final Optional<Integer> max;

    private final Map<String, Object> additionalProperties;

    private GetOrganizationInvitationsRequest(
            Optional<String> search,
            Optional<Integer> first,
            Optional<Integer> max,
            Map<String, Object> additionalProperties) {
        this.search = search;
        this.first = first;
        this.max = max;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("search")
    public Optional<String> getSearch() {
        return search;
    }

    @JsonProperty("first")
    public Optional<Integer> getFirst() {
        return first;
    }

    @JsonProperty("max")
    public Optional<Integer> getMax() {
        return max;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetOrganizationInvitationsRequest && equalTo((GetOrganizationInvitationsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetOrganizationInvitationsRequest other) {
        return search.equals(other.search) && first.equals(other.first) && max.equals(other.max);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.search, this.first, this.max);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> search = Optional.empty();

        private Optional<Integer> first = Optional.empty();

        private Optional<Integer> max = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetOrganizationInvitationsRequest other) {
            search(other.getSearch());
            first(other.getFirst());
            max(other.getMax());
            return this;
        }

        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(Optional<String> search) {
            this.search = search;
            return this;
        }

        public Builder search(String search) {
            this.search = Optional.ofNullable(search);
            return this;
        }

        @JsonSetter(value = "first", nulls = Nulls.SKIP)
        public Builder first(Optional<Integer> first) {
            this.first = first;
            return this;
        }

        public Builder first(Integer first) {
            this.first = Optional.ofNullable(first);
            return this;
        }

        @JsonSetter(value = "max", nulls = Nulls.SKIP)
        public Builder max(Optional<Integer> max) {
            this.max = max;
            return this;
        }

        public Builder max(Integer max) {
            this.max = Optional.ofNullable(max);
            return this;
        }

        public GetOrganizationInvitationsRequest build() {
            return new GetOrganizationInvitationsRequest(search, first, max, additionalProperties);
        }
    }
}
