/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrganizationMemberAttributeRepresentation.Builder.class)
public final class OrganizationMemberAttributeRepresentation {
    private final Optional<Map<String, List<String>>> attributes;

    private final Map<String, Object> additionalProperties;

    private OrganizationMemberAttributeRepresentation(
            Optional<Map<String, List<String>>> attributes, Map<String, Object> additionalProperties) {
        this.attributes = attributes;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("attributes")
    public Optional<Map<String, List<String>>> getAttributes() {
        return attributes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrganizationMemberAttributeRepresentation
                && equalTo((OrganizationMemberAttributeRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrganizationMemberAttributeRepresentation other) {
        return attributes.equals(other.attributes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attributes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<String, List<String>>> attributes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(OrganizationMemberAttributeRepresentation other) {
            attributes(other.getAttributes());
            return this;
        }

        @JsonSetter(value = "attributes", nulls = Nulls.SKIP)
        public Builder attributes(Optional<Map<String, List<String>>> attributes) {
            this.attributes = attributes;
            return this;
        }

        public Builder attributes(Map<String, List<String>> attributes) {
            this.attributes = Optional.ofNullable(attributes);
            return this;
        }

        public OrganizationMemberAttributeRepresentation build() {
            return new OrganizationMemberAttributeRepresentation(attributes, additionalProperties);
        }
    }
}
