/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.phasetwo.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RealmEventsConfigRepresentation.Builder.class)
public final class RealmEventsConfigRepresentation {
    private final Optional<Boolean> eventsEnabled;

    private final Optional<Long> eventsExpiration;

    private final Optional<List<String>> eventsListeners;

    private final Optional<List<String>> enabledEventTypes;

    private final Optional<Boolean> adminEventsEnabled;

    private final Optional<Boolean> adminEventsDetailsEnabled;

    private final Map<String, Object> additionalProperties;

    private RealmEventsConfigRepresentation(
            Optional<Boolean> eventsEnabled,
            Optional<Long> eventsExpiration,
            Optional<List<String>> eventsListeners,
            Optional<List<String>> enabledEventTypes,
            Optional<Boolean> adminEventsEnabled,
            Optional<Boolean> adminEventsDetailsEnabled,
            Map<String, Object> additionalProperties) {
        this.eventsEnabled = eventsEnabled;
        this.eventsExpiration = eventsExpiration;
        this.eventsListeners = eventsListeners;
        this.enabledEventTypes = enabledEventTypes;
        this.adminEventsEnabled = adminEventsEnabled;
        this.adminEventsDetailsEnabled = adminEventsDetailsEnabled;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("eventsEnabled")
    public Optional<Boolean> getEventsEnabled() {
        return eventsEnabled;
    }

    @JsonProperty("eventsExpiration")
    public Optional<Long> getEventsExpiration() {
        return eventsExpiration;
    }

    @JsonProperty("eventsListeners")
    public Optional<List<String>> getEventsListeners() {
        return eventsListeners;
    }

    @JsonProperty("enabledEventTypes")
    public Optional<List<String>> getEnabledEventTypes() {
        return enabledEventTypes;
    }

    @JsonProperty("adminEventsEnabled")
    public Optional<Boolean> getAdminEventsEnabled() {
        return adminEventsEnabled;
    }

    @JsonProperty("adminEventsDetailsEnabled")
    public Optional<Boolean> getAdminEventsDetailsEnabled() {
        return adminEventsDetailsEnabled;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RealmEventsConfigRepresentation && equalTo((RealmEventsConfigRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RealmEventsConfigRepresentation other) {
        return eventsEnabled.equals(other.eventsEnabled)
                && eventsExpiration.equals(other.eventsExpiration)
                && eventsListeners.equals(other.eventsListeners)
                && enabledEventTypes.equals(other.enabledEventTypes)
                && adminEventsEnabled.equals(other.adminEventsEnabled)
                && adminEventsDetailsEnabled.equals(other.adminEventsDetailsEnabled);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.eventsEnabled,
                this.eventsExpiration,
                this.eventsListeners,
                this.enabledEventTypes,
                this.adminEventsEnabled,
                this.adminEventsDetailsEnabled);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> eventsEnabled = Optional.empty();

        private Optional<Long> eventsExpiration = Optional.empty();

        private Optional<List<String>> eventsListeners = Optional.empty();

        private Optional<List<String>> enabledEventTypes = Optional.empty();

        private Optional<Boolean> adminEventsEnabled = Optional.empty();

        private Optional<Boolean> adminEventsDetailsEnabled = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(RealmEventsConfigRepresentation other) {
            eventsEnabled(other.getEventsEnabled());
            eventsExpiration(other.getEventsExpiration());
            eventsListeners(other.getEventsListeners());
            enabledEventTypes(other.getEnabledEventTypes());
            adminEventsEnabled(other.getAdminEventsEnabled());
            adminEventsDetailsEnabled(other.getAdminEventsDetailsEnabled());
            return this;
        }

        @JsonSetter(value = "eventsEnabled", nulls = Nulls.SKIP)
        public Builder eventsEnabled(Optional<Boolean> eventsEnabled) {
            this.eventsEnabled = eventsEnabled;
            return this;
        }

        public Builder eventsEnabled(Boolean eventsEnabled) {
            this.eventsEnabled = Optional.ofNullable(eventsEnabled);
            return this;
        }

        @JsonSetter(value = "eventsExpiration", nulls = Nulls.SKIP)
        public Builder eventsExpiration(Optional<Long> eventsExpiration) {
            this.eventsExpiration = eventsExpiration;
            return this;
        }

        public Builder eventsExpiration(Long eventsExpiration) {
            this.eventsExpiration = Optional.ofNullable(eventsExpiration);
            return this;
        }

        @JsonSetter(value = "eventsListeners", nulls = Nulls.SKIP)
        public Builder eventsListeners(Optional<List<String>> eventsListeners) {
            this.eventsListeners = eventsListeners;
            return this;
        }

        public Builder eventsListeners(List<String> eventsListeners) {
            this.eventsListeners = Optional.ofNullable(eventsListeners);
            return this;
        }

        @JsonSetter(value = "enabledEventTypes", nulls = Nulls.SKIP)
        public Builder enabledEventTypes(Optional<List<String>> enabledEventTypes) {
            this.enabledEventTypes = enabledEventTypes;
            return this;
        }

        public Builder enabledEventTypes(List<String> enabledEventTypes) {
            this.enabledEventTypes = Optional.ofNullable(enabledEventTypes);
            return this;
        }

        @JsonSetter(value = "adminEventsEnabled", nulls = Nulls.SKIP)
        public Builder adminEventsEnabled(Optional<Boolean> adminEventsEnabled) {
            this.adminEventsEnabled = adminEventsEnabled;
            return this;
        }

        public Builder adminEventsEnabled(Boolean adminEventsEnabled) {
            this.adminEventsEnabled = Optional.ofNullable(adminEventsEnabled);
            return this;
        }

        @JsonSetter(value = "adminEventsDetailsEnabled", nulls = Nulls.SKIP)
        public Builder adminEventsDetailsEnabled(Optional<Boolean> adminEventsDetailsEnabled) {
            this.adminEventsDetailsEnabled = adminEventsDetailsEnabled;
            return this;
        }

        public Builder adminEventsDetailsEnabled(Boolean adminEventsDetailsEnabled) {
            this.adminEventsDetailsEnabled = Optional.ofNullable(adminEventsDetailsEnabled);
            return this;
        }

        public RealmEventsConfigRepresentation build() {
            return new RealmEventsConfigRepresentation(
                    eventsEnabled,
                    eventsExpiration,
                    eventsListeners,
                    enabledEventTypes,
                    adminEventsEnabled,
                    adminEventsDetailsEnabled,
                    additionalProperties);
        }
    }
}
