/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.organizations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.ObjectMappers;
import com.phasetwo.core.PhasetwoApiException;
import com.phasetwo.core.PhasetwoClientHttpResponse;
import com.phasetwo.core.PhasetwoException;
import com.phasetwo.core.QueryStringMapper;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.organizations.types.MembershipsCountMembershipsRequest;
import com.phasetwo.organizations.types.MembershipsGetMembershipsRequest;
import com.phasetwo.types.UserWithOrgsBriefRepresentation;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawMembershipsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawMembershipsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<PhasetwoClientHttpResponse<List<UserWithOrgsBriefRepresentation>>> getMemberships(
            String realm, String orgId) {
        return getMemberships(
                realm, orgId, MembershipsGetMembershipsRequest.builder().build());
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<PhasetwoClientHttpResponse<List<UserWithOrgsBriefRepresentation>>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request) {
        return getMemberships(realm, orgId, request, null);
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<PhasetwoClientHttpResponse<List<UserWithOrgsBriefRepresentation>>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members");
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get().toString(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max", request.getMax().get().toString(), false);
        }
        if (request.getExcludeAdminAccounts().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "excludeAdminAccounts",
                    request.getExcludeAdminAccounts().get().toString(),
                    false);
        }
        if (request.getIncludeOrgs().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "includeOrgs", request.getIncludeOrgs().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PhasetwoClientHttpResponse<List<UserWithOrgsBriefRepresentation>>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PhasetwoClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(),
                                        new TypeReference<List<UserWithOrgsBriefRepresentation>>() {}),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    future.completeExceptionally(new PhasetwoApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<PhasetwoClientHttpResponse<Integer>> countMemberships(String realm, String orgId) {
        return countMemberships(
                realm, orgId, MembershipsCountMembershipsRequest.builder().build());
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<PhasetwoClientHttpResponse<Integer>> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request) {
        return countMemberships(realm, orgId, request, null);
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<PhasetwoClientHttpResponse<Integer>> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members/count");
        if (request.getExcludeAdminAccounts().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "excludeAdminAccounts",
                    request.getExcludeAdminAccounts().get().toString(),
                    false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PhasetwoClientHttpResponse<Integer>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PhasetwoClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), int.class), response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    future.completeExceptionally(new PhasetwoApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<PhasetwoClientHttpResponse<Void>> isMember(String realm, String orgId, String userId) {
        return isMember(realm, orgId, userId, null);
    }

    public CompletableFuture<PhasetwoClientHttpResponse<Void>> isMember(
            String realm, String orgId, String userId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members")
                .addPathSegment(userId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PhasetwoClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PhasetwoClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    future.completeExceptionally(new PhasetwoApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PhasetwoException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
