/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo.organizations;

import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.organizations.types.MembershipsCountMembershipsRequest;
import com.phasetwo.organizations.types.MembershipsGetMembershipsRequest;
import com.phasetwo.types.UserWithOrgsBriefRepresentation;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncMembershipsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawMembershipsClient rawClient;

    public AsyncMembershipsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawMembershipsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawMembershipsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<List<UserWithOrgsBriefRepresentation>> getMemberships(String realm, String orgId) {
        return this.rawClient.getMemberships(realm, orgId).thenApply(response -> response.body());
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<List<UserWithOrgsBriefRepresentation>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request) {
        return this.rawClient.getMemberships(realm, orgId, request).thenApply(response -> response.body());
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public CompletableFuture<List<UserWithOrgsBriefRepresentation>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getMemberships(realm, orgId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<Integer> countMemberships(String realm, String orgId) {
        return this.rawClient.countMemberships(realm, orgId).thenApply(response -> response.body());
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<Integer> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request) {
        return this.rawClient.countMemberships(realm, orgId, request).thenApply(response -> response.body());
    }

    /**
     * Get total number of members of a given organization
     */
    public CompletableFuture<Integer> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .countMemberships(realm, orgId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<Void> isMember(String realm, String orgId, String userId) {
        return this.rawClient.isMember(realm, orgId, userId).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> isMember(String realm, String orgId, String userId, RequestOptions requestOptions) {
        return this.rawClient.isMember(realm, orgId, userId, requestOptions).thenApply(response -> response.body());
    }
}
