/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import it.auth.api.core.ClientOptions;
import it.auth.api.core.RequestOptions;
import it.auth.api.types.GlobalRequestResult;
import it.auth.api.types.RemoveUserSessionRequest;
import java.util.concurrent.CompletableFuture;

public class AsyncSessionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSessionsClient rawClient;

    public AsyncSessionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSessionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSessionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Remove all user sessions for this realm. Any client that has an admin URL will also be told to invalidate any sessions they have. For large numbers of sessions, this can take a long period to execute.
     */
    public CompletableFuture<GlobalRequestResult> removeAllSessions() {
        return this.rawClient.removeAllSessions().thenApply(response -> response.body());
    }

    /**
     * Remove all user sessions for this realm. Any client that has an admin URL will also be told to invalidate any sessions they have. For large numbers of sessions, this can take a long period to execute.
     */
    public CompletableFuture<GlobalRequestResult> removeAllSessions(RequestOptions requestOptions) {
        return this.rawClient.removeAllSessions(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Remove a specific user session. Any client that has an admin URL will also be told to invalidate this particular session.
     */
    public CompletableFuture<Void> removeUserSession(String session) {
        return this.rawClient.removeUserSession(session).thenApply(response -> response.body());
    }

    /**
     * Remove a specific user session. Any client that has an admin URL will also be told to invalidate this particular session.
     */
    public CompletableFuture<Void> removeUserSession(String session, RemoveUserSessionRequest request) {
        return this.rawClient.removeUserSession(session, request).thenApply(response -> response.body());
    }

    /**
     * Remove a specific user session. Any client that has an admin URL will also be told to invalidate this particular session.
     */
    public CompletableFuture<Void> removeUserSession(
            String session, RemoveUserSessionRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .removeUserSession(session, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
