/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import it.auth.api.core.AuthItApiException;
import it.auth.api.core.AuthItClientHttpResponse;
import it.auth.api.core.AuthItException;
import it.auth.api.core.ClientOptions;
import it.auth.api.core.MediaTypes;
import it.auth.api.core.ObjectMappers;
import it.auth.api.core.QueryStringMapper;
import it.auth.api.core.RequestOptions;
import it.auth.api.errors.BadRequestError;
import it.auth.api.errors.ConflictError;
import it.auth.api.errors.ForbiddenError;
import it.auth.api.types.AdminEventRepresentation;
import it.auth.api.types.AuditEventRepresentation;
import it.auth.api.types.EventRepresentation;
import it.auth.api.types.GetAdminEventsRequest;
import it.auth.api.types.GetEventsRequest;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawEventsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Delete all admin events in this realm
     */
    public CompletableFuture<AuthItClientHttpResponse<Void>> deleteAdminEvents(String realm) {
        return deleteAdminEvents(realm, null);
    }

    /**
     * Delete all admin events in this realm
     */
    public CompletableFuture<AuthItClientHttpResponse<Void>> deleteAdminEvents(
            String realm, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("admin-events")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<AuthItClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new AuthItClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 403) {
                            future.completeExceptionally(new ForbiddenError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new AuthItApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Delete all events in this realm
     */
    public CompletableFuture<AuthItClientHttpResponse<Void>> deleteEvents(String realm) {
        return deleteEvents(realm, null);
    }

    /**
     * Delete all events in this realm
     */
    public CompletableFuture<AuthItClientHttpResponse<Void>> deleteEvents(String realm, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("events")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<AuthItClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new AuthItClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 403) {
                            future.completeExceptionally(new ForbiddenError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new AuthItApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<AuthItClientHttpResponse<Void>> createEvent(String realm) {
        return createEvent(realm, AuditEventRepresentation.builder().build());
    }

    public CompletableFuture<AuthItClientHttpResponse<Void>> createEvent(
            String realm, AuditEventRepresentation request) {
        return createEvent(realm, request, null);
    }

    public CompletableFuture<AuthItClientHttpResponse<Void>> createEvent(
            String realm, AuditEventRepresentation request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("events")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AuthItException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<AuthItClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new AuthItClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new AuthItApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<EventRepresentation>>> getEvents(String realm) {
        return getEvents(realm, GetEventsRequest.builder().build());
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<EventRepresentation>>> getEvents(
            String realm, GetEventsRequest request) {
        return getEvents(realm, request, null);
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<EventRepresentation>>> getEvents(
            String realm, GetEventsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("ext-admin/events/events");
        if (request.getClient().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "client", request.getClient().get(), false);
        }
        if (request.getDateFrom().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "dateFrom", request.getDateFrom().get(), false);
        }
        if (request.getDateTo().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "dateTo", request.getDateTo().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get().toString(), false);
        }
        if (request.getIpAddress().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "ipAddress", request.getIpAddress().get(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max", request.getMax().get().toString(), false);
        }
        if (request.getUser().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "user", request.getUser().get(), false);
        }
        if (request.getType().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "type", request.getType().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<AuthItClientHttpResponse<List<EventRepresentation>>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new AuthItClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), new TypeReference<List<EventRepresentation>>() {}),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    future.completeExceptionally(new AuthItApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<AdminEventRepresentation>>> getAdminEvents(String realm) {
        return getAdminEvents(realm, GetAdminEventsRequest.builder().build());
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<AdminEventRepresentation>>> getAdminEvents(
            String realm, GetAdminEventsRequest request) {
        return getAdminEvents(realm, request, null);
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<AuthItClientHttpResponse<List<AdminEventRepresentation>>> getAdminEvents(
            String realm, GetAdminEventsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("ext-admin/events/admin-events");
        if (request.getAuthClient().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "authClient", request.getAuthClient().get(), false);
        }
        if (request.getAuthIpAddress().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "authIpAddress", request.getAuthIpAddress().get(), false);
        }
        if (request.getAuthRealm().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "authRealm", request.getAuthRealm().get(), false);
        }
        if (request.getAuthUser().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "authUser", request.getAuthUser().get(), false);
        }
        if (request.getDateFrom().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "dateFrom", request.getDateFrom().get(), false);
        }
        if (request.getDateTo().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "dateTo", request.getDateTo().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get().toString(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max", request.getMax().get().toString(), false);
        }
        if (request.getResourcePath().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "resourcePath", request.getResourcePath().get(), false);
        }
        if (request.getOperationTypes().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "operationTypes", request.getOperationTypes().get().toString(), false);
        }
        if (request.getResourceTypes().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "resourceTypes", request.getResourceTypes().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<AuthItClientHttpResponse<List<AdminEventRepresentation>>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new AuthItClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), new TypeReference<List<AdminEventRepresentation>>() {}),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    future.completeExceptionally(new AuthItApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AuthItException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
