/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import it.auth.api.core.ClientOptions;
import it.auth.api.core.Suppliers;
import java.util.function.Supplier;

public class AsyncAuthItClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncEventsClient> eventsClient;

    protected final Supplier<AsyncAttackDetectionClient> attackDetectionClient;

    protected final Supplier<AsyncSessionsClient> sessionsClient;

    protected final Supplier<AsyncRolesClient> rolesClient;

    protected final Supplier<AsyncUsersClient> usersClient;

    protected final Supplier<AsyncRoleMapperClient> roleMapperClient;

    protected final Supplier<AsyncOrganizationsClient> organizationsClient;

    public AsyncAuthItClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.eventsClient = Suppliers.memoize(() -> new AsyncEventsClient(clientOptions));
        this.attackDetectionClient = Suppliers.memoize(() -> new AsyncAttackDetectionClient(clientOptions));
        this.sessionsClient = Suppliers.memoize(() -> new AsyncSessionsClient(clientOptions));
        this.rolesClient = Suppliers.memoize(() -> new AsyncRolesClient(clientOptions));
        this.usersClient = Suppliers.memoize(() -> new AsyncUsersClient(clientOptions));
        this.roleMapperClient = Suppliers.memoize(() -> new AsyncRoleMapperClient(clientOptions));
        this.organizationsClient = Suppliers.memoize(() -> new AsyncOrganizationsClient(clientOptions));
    }

    public AsyncEventsClient events() {
        return this.eventsClient.get();
    }

    public AsyncAttackDetectionClient attackDetection() {
        return this.attackDetectionClient.get();
    }

    public AsyncSessionsClient sessions() {
        return this.sessionsClient.get();
    }

    public AsyncRolesClient roles() {
        return this.rolesClient.get();
    }

    public AsyncUsersClient users() {
        return this.usersClient.get();
    }

    public AsyncRoleMapperClient roleMapper() {
        return this.roleMapperClient.get();
    }

    public AsyncOrganizationsClient organizations() {
        return this.organizationsClient.get();
    }

    public static AsyncAuthItClientBuilder builder() {
        return new AsyncAuthItClientBuilder();
    }
}
