/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import it.auth.api.core.ClientOptions;
import it.auth.api.core.RequestOptions;
import it.auth.api.core.Suppliers;
import it.auth.api.events.AsyncWebhooksClient;
import it.auth.api.types.AdminEventRepresentation;
import it.auth.api.types.AuditEventRepresentation;
import it.auth.api.types.EventRepresentation;
import it.auth.api.types.GetAdminEventsRequest;
import it.auth.api.types.GetEventsRequest;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncEventsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEventsClient rawClient;

    protected final Supplier<AsyncWebhooksClient> webhooksClient;

    public AsyncEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEventsClient(clientOptions);
        this.webhooksClient = Suppliers.memoize(() -> new AsyncWebhooksClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEventsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Delete all admin events in this realm
     */
    public CompletableFuture<Void> deleteAdminEvents(String realm) {
        return this.rawClient.deleteAdminEvents(realm).thenApply(response -> response.body());
    }

    /**
     * Delete all admin events in this realm
     */
    public CompletableFuture<Void> deleteAdminEvents(String realm, RequestOptions requestOptions) {
        return this.rawClient.deleteAdminEvents(realm, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete all events in this realm
     */
    public CompletableFuture<Void> deleteEvents(String realm) {
        return this.rawClient.deleteEvents(realm).thenApply(response -> response.body());
    }

    /**
     * Delete all events in this realm
     */
    public CompletableFuture<Void> deleteEvents(String realm, RequestOptions requestOptions) {
        return this.rawClient.deleteEvents(realm, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(String realm) {
        return this.rawClient.createEvent(realm).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(String realm, AuditEventRepresentation request) {
        return this.rawClient.createEvent(realm, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(
            String realm, AuditEventRepresentation request, RequestOptions requestOptions) {
        return this.rawClient.createEvent(realm, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<List<EventRepresentation>> getEvents(String realm) {
        return this.rawClient.getEvents(realm).thenApply(response -> response.body());
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<List<EventRepresentation>> getEvents(String realm, GetEventsRequest request) {
        return this.rawClient.getEvents(realm, request).thenApply(response -> response.body());
    }

    /**
     * Get all events, or filters them based on URL query parameters.
     */
    public CompletableFuture<List<EventRepresentation>> getEvents(
            String realm, GetEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getEvents(realm, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<List<AdminEventRepresentation>> getAdminEvents(String realm) {
        return this.rawClient.getAdminEvents(realm).thenApply(response -> response.body());
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<List<AdminEventRepresentation>> getAdminEvents(
            String realm, GetAdminEventsRequest request) {
        return this.rawClient.getAdminEvents(realm, request).thenApply(response -> response.body());
    }

    /**
     * Get all admin events, or filters events based on URL query parameters.
     */
    public CompletableFuture<List<AdminEventRepresentation>> getAdminEvents(
            String realm, GetAdminEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAdminEvents(realm, request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncWebhooksClient webhooks() {
        return this.webhooksClient.get();
    }
}
