/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import it.auth.api.core.AuthItApiException;
import it.auth.api.core.AuthItClientHttpResponse;
import it.auth.api.core.AuthItException;
import it.auth.api.core.ClientOptions;
import it.auth.api.core.MediaTypes;
import it.auth.api.core.ObjectMappers;
import it.auth.api.core.QueryStringMapper;
import it.auth.api.core.RequestOptions;
import it.auth.api.errors.BadRequestError;
import it.auth.api.errors.ConflictError;
import it.auth.api.errors.ForbiddenError;
import it.auth.api.errors.InternalServerError;
import it.auth.api.errors.NotFoundError;
import it.auth.api.types.GetRolesRequest;
import it.auth.api.types.GetUsersByRoleRequest;
import it.auth.api.types.RoleRepresentation;
import it.auth.api.types.UserRepresentation;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawRolesClient {
    protected final ClientOptions clientOptions;

    public RawRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get all roles for the given realm or client.
     */
    public AuthItClientHttpResponse<List<RoleRepresentation>> getRoles() {
        return getRoles(GetRolesRequest.builder().build());
    }

    /**
     * Get all roles for the given realm or client.
     */
    public AuthItClientHttpResponse<List<RoleRepresentation>> getRoles(GetRolesRequest request) {
        return getRoles(request, null);
    }

    /**
     * Get all roles for the given realm or client.
     */
    public AuthItClientHttpResponse<List<RoleRepresentation>> getRoles(
            GetRolesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles");
        if (request.getBriefRepresentation().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "briefRepresentation",
                    request.getBriefRepresentation().get(),
                    false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "max", request.getMax().get(), false);
        }
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<List<RoleRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                if (response.code() == 403) {
                    throw new ForbiddenError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Create a new role for the realm or client.
     */
    public AuthItClientHttpResponse<Void> createRole() {
        return createRole(RoleRepresentation.builder().build());
    }

    /**
     * Create a new role for the realm or client.
     */
    public AuthItClientHttpResponse<Void> createRole(RoleRepresentation request) {
        return createRole(request, null);
    }

    /**
     * Create a new role for the realm or client.
     */
    public AuthItClientHttpResponse<Void> createRole(RoleRepresentation request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AuthItException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a role by name.
     */
    public AuthItClientHttpResponse<RoleRepresentation> getRole(String roleName) {
        return getRole(roleName, null);
    }

    /**
     * Get a role by name.
     */
    public AuthItClientHttpResponse<RoleRepresentation> getRole(String roleName, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles")
                .addPathSegment(roleName)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), RoleRepresentation.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update a role by name.
     */
    public AuthItClientHttpResponse<Void> updateRole(String roleName) {
        return updateRole(roleName, RoleRepresentation.builder().build());
    }

    /**
     * Update a role by name.
     */
    public AuthItClientHttpResponse<Void> updateRole(String roleName, RoleRepresentation request) {
        return updateRole(roleName, request, null);
    }

    /**
     * Update a role by name.
     */
    public AuthItClientHttpResponse<Void> updateRole(
            String roleName, RoleRepresentation request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles")
                .addPathSegment(roleName)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AuthItException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Delete a role by name.
     */
    public AuthItClientHttpResponse<Void> deleteRole(String roleName) {
        return deleteRole(roleName, null);
    }

    /**
     * Delete a role by name.
     */
    public AuthItClientHttpResponse<Void> deleteRole(String roleName, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles")
                .addPathSegment(roleName)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public AuthItClientHttpResponse<List<UserRepresentation>> getUsersByRole(String roleName) {
        return getUsersByRole(roleName, GetUsersByRoleRequest.builder().build());
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public AuthItClientHttpResponse<List<UserRepresentation>> getUsersByRole(
            String roleName, GetUsersByRoleRequest request) {
        return getUsersByRole(roleName, request, null);
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public AuthItClientHttpResponse<List<UserRepresentation>> getUsersByRole(
            String roleName, GetUsersByRoleRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(clientOptions.realm())
                .addPathSegments("roles")
                .addPathSegment(roleName)
                .addPathSegments("users");
        if (request.getBriefRepresentation().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "briefRepresentation",
                    request.getBriefRepresentation().get(),
                    false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "max", request.getMax().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<List<UserRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }
}
