/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api;

import it.auth.api.core.ClientOptions;
import it.auth.api.core.RequestOptions;
import it.auth.api.core.Suppliers;
import it.auth.api.roles.MappingsClient;
import it.auth.api.types.GetRolesRequest;
import it.auth.api.types.GetUsersByRoleRequest;
import it.auth.api.types.RoleRepresentation;
import it.auth.api.types.UserRepresentation;
import java.util.List;
import java.util.function.Supplier;

public class RolesClient {
    protected final ClientOptions clientOptions;

    private final RawRolesClient rawClient;

    protected final Supplier<MappingsClient> mappingsClient;

    public RolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRolesClient(clientOptions);
        this.mappingsClient = Suppliers.memoize(() -> new MappingsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRolesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get all roles for the given realm or client.
     */
    public List<RoleRepresentation> getRoles(String realm) {
        return this.rawClient.getRoles(realm).body();
    }

    /**
     * Get all roles for the given realm or client.
     */
    public List<RoleRepresentation> getRoles(String realm, GetRolesRequest request) {
        return this.rawClient.getRoles(realm, request).body();
    }

    /**
     * Get all roles for the given realm or client.
     */
    public List<RoleRepresentation> getRoles(String realm, GetRolesRequest request, RequestOptions requestOptions) {
        return this.rawClient.getRoles(realm, request, requestOptions).body();
    }

    /**
     * Create a new role for the realm or client.
     */
    public void createRole(String realm) {
        this.rawClient.createRole(realm).body();
    }

    /**
     * Create a new role for the realm or client.
     */
    public void createRole(String realm, RoleRepresentation request) {
        this.rawClient.createRole(realm, request).body();
    }

    /**
     * Create a new role for the realm or client.
     */
    public void createRole(String realm, RoleRepresentation request, RequestOptions requestOptions) {
        this.rawClient.createRole(realm, request, requestOptions).body();
    }

    /**
     * Get a role by name.
     */
    public RoleRepresentation getRole(String realm, String roleName) {
        return this.rawClient.getRole(realm, roleName).body();
    }

    /**
     * Get a role by name.
     */
    public RoleRepresentation getRole(String realm, String roleName, RequestOptions requestOptions) {
        return this.rawClient.getRole(realm, roleName, requestOptions).body();
    }

    /**
     * Update a role by name.
     */
    public void updateRole(String realm, String roleName) {
        this.rawClient.updateRole(realm, roleName).body();
    }

    /**
     * Update a role by name.
     */
    public void updateRole(String realm, String roleName, RoleRepresentation request) {
        this.rawClient.updateRole(realm, roleName, request).body();
    }

    /**
     * Update a role by name.
     */
    public void updateRole(String realm, String roleName, RoleRepresentation request, RequestOptions requestOptions) {
        this.rawClient.updateRole(realm, roleName, request, requestOptions).body();
    }

    /**
     * Delete a role by name.
     */
    public void deleteRole(String realm, String roleName) {
        this.rawClient.deleteRole(realm, roleName).body();
    }

    /**
     * Delete a role by name.
     */
    public void deleteRole(String realm, String roleName, RequestOptions requestOptions) {
        this.rawClient.deleteRole(realm, roleName, requestOptions).body();
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public List<UserRepresentation> getUsersByRole(String realm, String roleName) {
        return this.rawClient.getUsersByRole(realm, roleName).body();
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public List<UserRepresentation> getUsersByRole(String realm, String roleName, GetUsersByRoleRequest request) {
        return this.rawClient.getUsersByRole(realm, roleName, request).body();
    }

    /**
     * Get users that have the specified role name assigned.
     */
    public List<UserRepresentation> getUsersByRole(
            String realm, String roleName, GetUsersByRoleRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getUsersByRole(realm, roleName, request, requestOptions)
                .body();
    }

    public MappingsClient mappings() {
        return this.mappingsClient.get();
    }
}
