/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.organizations;

import it.auth.api.core.ClientOptions;
import it.auth.api.core.RequestOptions;
import it.auth.api.types.OrganizationDomainRepresentation;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncDomainsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawDomainsClient rawClient;

    public AsyncDomainsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawDomainsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawDomainsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get details for all domains owned by an organization.
     */
    public CompletableFuture<List<OrganizationDomainRepresentation>> getDomains(String orgId) {
        return this.rawClient.getDomains(orgId).thenApply(response -> response.body());
    }

    /**
     * Get details for all domains owned by an organization.
     */
    public CompletableFuture<List<OrganizationDomainRepresentation>> getDomains(
            String orgId, RequestOptions requestOptions) {
        return this.rawClient.getDomains(orgId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get details for a domain owned by an organization.
     */
    public CompletableFuture<OrganizationDomainRepresentation> getDomain(String orgId, String domainName) {
        return this.rawClient.getDomain(orgId, domainName).thenApply(response -> response.body());
    }

    /**
     * Get details for a domain owned by an organization.
     */
    public CompletableFuture<OrganizationDomainRepresentation> getDomain(
            String orgId, String domainName, RequestOptions requestOptions) {
        return this.rawClient.getDomain(orgId, domainName, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Initiate a verification check for the domain name owned by this organization.
     */
    public CompletableFuture<Void> verifyDomain(String orgId, String domainName) {
        return this.rawClient.verifyDomain(orgId, domainName).thenApply(response -> response.body());
    }

    /**
     * Initiate a verification check for the domain name owned by this organization.
     */
    public CompletableFuture<Void> verifyDomain(String orgId, String domainName, RequestOptions requestOptions) {
        return this.rawClient.verifyDomain(orgId, domainName, requestOptions).thenApply(response -> response.body());
    }
}
