/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.organizations;

import com.fasterxml.jackson.core.type.TypeReference;
import it.auth.api.core.AuthItApiException;
import it.auth.api.core.AuthItClientHttpResponse;
import it.auth.api.core.AuthItException;
import it.auth.api.core.ClientOptions;
import it.auth.api.core.ObjectMappers;
import it.auth.api.core.QueryStringMapper;
import it.auth.api.core.RequestOptions;
import it.auth.api.organizations.types.MembershipsCountMembershipsRequest;
import it.auth.api.organizations.types.MembershipsGetMembershipsRequest;
import it.auth.api.types.UserWithOrgsBriefRepresentation;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawMembershipsClient {
    protected final ClientOptions clientOptions;

    public RawMembershipsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public AuthItClientHttpResponse<List<UserWithOrgsBriefRepresentation>> getMemberships(String realm, String orgId) {
        return getMemberships(
                realm, orgId, MembershipsGetMembershipsRequest.builder().build());
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public AuthItClientHttpResponse<List<UserWithOrgsBriefRepresentation>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request) {
        return getMemberships(realm, orgId, request, null);
    }

    /**
     * Get a paginated list of users who are a member of the specified organization.
     */
    public AuthItClientHttpResponse<List<UserWithOrgsBriefRepresentation>> getMemberships(
            String realm, String orgId, MembershipsGetMembershipsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members");
        if (request.getSearch().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "search", request.getSearch().get(), false);
        }
        if (request.getFirst().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "first", request.getFirst().get().toString(), false);
        }
        if (request.getMax().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max", request.getMax().get().toString(), false);
        }
        if (request.getExcludeAdminAccounts().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "excludeAdminAccounts",
                    request.getExcludeAdminAccounts().get().toString(),
                    false);
        }
        if (request.getIncludeOrgs().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "includeOrgs", request.getIncludeOrgs().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<List<UserWithOrgsBriefRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get total number of members of a given organization
     */
    public AuthItClientHttpResponse<Integer> countMemberships(String realm, String orgId) {
        return countMemberships(
                realm, orgId, MembershipsCountMembershipsRequest.builder().build());
    }

    /**
     * Get total number of members of a given organization
     */
    public AuthItClientHttpResponse<Integer> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request) {
        return countMemberships(realm, orgId, request, null);
    }

    /**
     * Get total number of members of a given organization
     */
    public AuthItClientHttpResponse<Integer> countMemberships(
            String realm, String orgId, MembershipsCountMembershipsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members/count");
        if (request.getExcludeAdminAccounts().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "excludeAdminAccounts",
                    request.getExcludeAdminAccounts().get().toString(),
                    false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), int.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }

    public AuthItClientHttpResponse<Void> isMember(String realm, String orgId, String userId) {
        return isMember(realm, orgId, userId, null);
    }

    public AuthItClientHttpResponse<Void> isMember(
            String realm, String orgId, String userId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("members")
                .addPathSegment(userId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new AuthItClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new AuthItApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new AuthItException("Network error executing HTTP request", e);
        }
    }
}
