/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import it.auth.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthDetailsRepresentation.Builder.class)
public final class AuthDetailsRepresentation {
    private final Optional<String> realmId;

    private final Optional<String> clientId;

    private final Optional<String> userId;

    private final Optional<String> ipAddress;

    private final Optional<String> username;

    private final Optional<String> sessionId;

    private final Map<String, Object> additionalProperties;

    private AuthDetailsRepresentation(
            Optional<String> realmId,
            Optional<String> clientId,
            Optional<String> userId,
            Optional<String> ipAddress,
            Optional<String> username,
            Optional<String> sessionId,
            Map<String, Object> additionalProperties) {
        this.realmId = realmId;
        this.clientId = clientId;
        this.userId = userId;
        this.ipAddress = ipAddress;
        this.username = username;
        this.sessionId = sessionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("realmId")
    public Optional<String> getRealmId() {
        return realmId;
    }

    @JsonProperty("clientId")
    public Optional<String> getClientId() {
        return clientId;
    }

    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    @JsonProperty("ipAddress")
    public Optional<String> getIpAddress() {
        return ipAddress;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        return username;
    }

    @JsonProperty("sessionId")
    public Optional<String> getSessionId() {
        return sessionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthDetailsRepresentation && equalTo((AuthDetailsRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthDetailsRepresentation other) {
        return realmId.equals(other.realmId)
                && clientId.equals(other.clientId)
                && userId.equals(other.userId)
                && ipAddress.equals(other.ipAddress)
                && username.equals(other.username)
                && sessionId.equals(other.sessionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.realmId, this.clientId, this.userId, this.ipAddress, this.username, this.sessionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> realmId = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<String> ipAddress = Optional.empty();

        private Optional<String> username = Optional.empty();

        private Optional<String> sessionId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AuthDetailsRepresentation other) {
            realmId(other.getRealmId());
            clientId(other.getClientId());
            userId(other.getUserId());
            ipAddress(other.getIpAddress());
            username(other.getUsername());
            sessionId(other.getSessionId());
            return this;
        }

        @JsonSetter(value = "realmId", nulls = Nulls.SKIP)
        public Builder realmId(Optional<String> realmId) {
            this.realmId = realmId;
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Optional.ofNullable(realmId);
            return this;
        }

        @JsonSetter(value = "clientId", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @JsonSetter(value = "ipAddress", nulls = Nulls.SKIP)
        public Builder ipAddress(Optional<String> ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }

        public Builder ipAddress(String ipAddress) {
            this.ipAddress = Optional.ofNullable(ipAddress);
            return this;
        }

        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public Builder username(Optional<String> username) {
            this.username = username;
            return this;
        }

        public Builder username(String username) {
            this.username = Optional.ofNullable(username);
            return this;
        }

        @JsonSetter(value = "sessionId", nulls = Nulls.SKIP)
        public Builder sessionId(Optional<String> sessionId) {
            this.sessionId = sessionId;
            return this;
        }

        public Builder sessionId(String sessionId) {
            this.sessionId = Optional.ofNullable(sessionId);
            return this;
        }

        public AuthDetailsRepresentation build() {
            return new AuthDetailsRepresentation(
                    realmId, clientId, userId, ipAddress, username, sessionId, additionalProperties);
        }
    }
}
