/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import it.auth.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MagicLinkRequest.Builder.class)
public final class MagicLinkRequest {
    private final String email;

    private final String clientId;

    private final String redirectUri;

    private final Optional<Integer> expirationSeconds;

    private final Optional<Boolean> forceCreate;

    private final Optional<Boolean> sendEmail;

    private final Optional<Boolean> updateProfile;

    private final Optional<Boolean> updatePassword;

    private final Optional<String> scope;

    private final Optional<String> nonce;

    private final Optional<String> codeChallenge;

    private final Optional<String> codeChallengeMethod;

    private final Optional<Boolean> rememberMe;

    private final Optional<Boolean> reusable;

    private final Map<String, Object> additionalProperties;

    private MagicLinkRequest(
            String email,
            String clientId,
            String redirectUri,
            Optional<Integer> expirationSeconds,
            Optional<Boolean> forceCreate,
            Optional<Boolean> sendEmail,
            Optional<Boolean> updateProfile,
            Optional<Boolean> updatePassword,
            Optional<String> scope,
            Optional<String> nonce,
            Optional<String> codeChallenge,
            Optional<String> codeChallengeMethod,
            Optional<Boolean> rememberMe,
            Optional<Boolean> reusable,
            Map<String, Object> additionalProperties) {
        this.email = email;
        this.clientId = clientId;
        this.redirectUri = redirectUri;
        this.expirationSeconds = expirationSeconds;
        this.forceCreate = forceCreate;
        this.sendEmail = sendEmail;
        this.updateProfile = updateProfile;
        this.updatePassword = updatePassword;
        this.scope = scope;
        this.nonce = nonce;
        this.codeChallenge = codeChallenge;
        this.codeChallengeMethod = codeChallengeMethod;
        this.rememberMe = rememberMe;
        this.reusable = reusable;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    @JsonProperty("client_id")
    public String getClientId() {
        return clientId;
    }

    @JsonProperty("redirect_uri")
    public String getRedirectUri() {
        return redirectUri;
    }

    @JsonProperty("expiration_seconds")
    public Optional<Integer> getExpirationSeconds() {
        return expirationSeconds;
    }

    @JsonProperty("force_create")
    public Optional<Boolean> getForceCreate() {
        return forceCreate;
    }

    @JsonProperty("send_email")
    public Optional<Boolean> getSendEmail() {
        return sendEmail;
    }

    @JsonProperty("update_profile")
    public Optional<Boolean> getUpdateProfile() {
        return updateProfile;
    }

    @JsonProperty("update_password")
    public Optional<Boolean> getUpdatePassword() {
        return updatePassword;
    }

    @JsonProperty("scope")
    public Optional<String> getScope() {
        return scope;
    }

    @JsonProperty("nonce")
    public Optional<String> getNonce() {
        return nonce;
    }

    @JsonProperty("code_challenge")
    public Optional<String> getCodeChallenge() {
        return codeChallenge;
    }

    @JsonProperty("code_challenge_method")
    public Optional<String> getCodeChallengeMethod() {
        return codeChallengeMethod;
    }

    @JsonProperty("remember_me")
    public Optional<Boolean> getRememberMe() {
        return rememberMe;
    }

    @JsonProperty("reusable")
    public Optional<Boolean> getReusable() {
        return reusable;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MagicLinkRequest && equalTo((MagicLinkRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MagicLinkRequest other) {
        return email.equals(other.email)
                && clientId.equals(other.clientId)
                && redirectUri.equals(other.redirectUri)
                && expirationSeconds.equals(other.expirationSeconds)
                && forceCreate.equals(other.forceCreate)
                && sendEmail.equals(other.sendEmail)
                && updateProfile.equals(other.updateProfile)
                && updatePassword.equals(other.updatePassword)
                && scope.equals(other.scope)
                && nonce.equals(other.nonce)
                && codeChallenge.equals(other.codeChallenge)
                && codeChallengeMethod.equals(other.codeChallengeMethod)
                && rememberMe.equals(other.rememberMe)
                && reusable.equals(other.reusable);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.email,
                this.clientId,
                this.redirectUri,
                this.expirationSeconds,
                this.forceCreate,
                this.sendEmail,
                this.updateProfile,
                this.updatePassword,
                this.scope,
                this.nonce,
                this.codeChallenge,
                this.codeChallengeMethod,
                this.rememberMe,
                this.reusable);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmailStage builder() {
        return new Builder();
    }

    public interface EmailStage {
        ClientIdStage email(@NotNull String email);

        Builder from(MagicLinkRequest other);
    }

    public interface ClientIdStage {
        RedirectUriStage clientId(@NotNull String clientId);
    }

    public interface RedirectUriStage {
        _FinalStage redirectUri(@NotNull String redirectUri);
    }

    public interface _FinalStage {
        MagicLinkRequest build();

        _FinalStage expirationSeconds(Optional<Integer> expirationSeconds);

        _FinalStage expirationSeconds(Integer expirationSeconds);

        _FinalStage forceCreate(Optional<Boolean> forceCreate);

        _FinalStage forceCreate(Boolean forceCreate);

        _FinalStage sendEmail(Optional<Boolean> sendEmail);

        _FinalStage sendEmail(Boolean sendEmail);

        _FinalStage updateProfile(Optional<Boolean> updateProfile);

        _FinalStage updateProfile(Boolean updateProfile);

        _FinalStage updatePassword(Optional<Boolean> updatePassword);

        _FinalStage updatePassword(Boolean updatePassword);

        _FinalStage scope(Optional<String> scope);

        _FinalStage scope(String scope);

        _FinalStage nonce(Optional<String> nonce);

        _FinalStage nonce(String nonce);

        _FinalStage codeChallenge(Optional<String> codeChallenge);

        _FinalStage codeChallenge(String codeChallenge);

        _FinalStage codeChallengeMethod(Optional<String> codeChallengeMethod);

        _FinalStage codeChallengeMethod(String codeChallengeMethod);

        _FinalStage rememberMe(Optional<Boolean> rememberMe);

        _FinalStage rememberMe(Boolean rememberMe);

        _FinalStage reusable(Optional<Boolean> reusable);

        _FinalStage reusable(Boolean reusable);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EmailStage, ClientIdStage, RedirectUriStage, _FinalStage {
        private String email;

        private String clientId;

        private String redirectUri;

        private Optional<Boolean> reusable = Optional.empty();

        private Optional<Boolean> rememberMe = Optional.empty();

        private Optional<String> codeChallengeMethod = Optional.empty();

        private Optional<String> codeChallenge = Optional.empty();

        private Optional<String> nonce = Optional.empty();

        private Optional<String> scope = Optional.empty();

        private Optional<Boolean> updatePassword = Optional.empty();

        private Optional<Boolean> updateProfile = Optional.empty();

        private Optional<Boolean> sendEmail = Optional.empty();

        private Optional<Boolean> forceCreate = Optional.empty();

        private Optional<Integer> expirationSeconds = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MagicLinkRequest other) {
            email(other.getEmail());
            clientId(other.getClientId());
            redirectUri(other.getRedirectUri());
            expirationSeconds(other.getExpirationSeconds());
            forceCreate(other.getForceCreate());
            sendEmail(other.getSendEmail());
            updateProfile(other.getUpdateProfile());
            updatePassword(other.getUpdatePassword());
            scope(other.getScope());
            nonce(other.getNonce());
            codeChallenge(other.getCodeChallenge());
            codeChallengeMethod(other.getCodeChallengeMethod());
            rememberMe(other.getRememberMe());
            reusable(other.getReusable());
            return this;
        }

        @java.lang.Override
        @JsonSetter("email")
        public ClientIdStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("client_id")
        public RedirectUriStage clientId(@NotNull String clientId) {
            this.clientId = Objects.requireNonNull(clientId, "clientId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("redirect_uri")
        public _FinalStage redirectUri(@NotNull String redirectUri) {
            this.redirectUri = Objects.requireNonNull(redirectUri, "redirectUri must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage reusable(Boolean reusable) {
            this.reusable = Optional.ofNullable(reusable);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "reusable", nulls = Nulls.SKIP)
        public _FinalStage reusable(Optional<Boolean> reusable) {
            this.reusable = reusable;
            return this;
        }

        @java.lang.Override
        public _FinalStage rememberMe(Boolean rememberMe) {
            this.rememberMe = Optional.ofNullable(rememberMe);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "remember_me", nulls = Nulls.SKIP)
        public _FinalStage rememberMe(Optional<Boolean> rememberMe) {
            this.rememberMe = rememberMe;
            return this;
        }

        @java.lang.Override
        public _FinalStage codeChallengeMethod(String codeChallengeMethod) {
            this.codeChallengeMethod = Optional.ofNullable(codeChallengeMethod);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "code_challenge_method", nulls = Nulls.SKIP)
        public _FinalStage codeChallengeMethod(Optional<String> codeChallengeMethod) {
            this.codeChallengeMethod = codeChallengeMethod;
            return this;
        }

        @java.lang.Override
        public _FinalStage codeChallenge(String codeChallenge) {
            this.codeChallenge = Optional.ofNullable(codeChallenge);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "code_challenge", nulls = Nulls.SKIP)
        public _FinalStage codeChallenge(Optional<String> codeChallenge) {
            this.codeChallenge = codeChallenge;
            return this;
        }

        @java.lang.Override
        public _FinalStage nonce(String nonce) {
            this.nonce = Optional.ofNullable(nonce);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "nonce", nulls = Nulls.SKIP)
        public _FinalStage nonce(Optional<String> nonce) {
            this.nonce = nonce;
            return this;
        }

        @java.lang.Override
        public _FinalStage scope(String scope) {
            this.scope = Optional.ofNullable(scope);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "scope", nulls = Nulls.SKIP)
        public _FinalStage scope(Optional<String> scope) {
            this.scope = scope;
            return this;
        }

        @java.lang.Override
        public _FinalStage updatePassword(Boolean updatePassword) {
            this.updatePassword = Optional.ofNullable(updatePassword);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "update_password", nulls = Nulls.SKIP)
        public _FinalStage updatePassword(Optional<Boolean> updatePassword) {
            this.updatePassword = updatePassword;
            return this;
        }

        @java.lang.Override
        public _FinalStage updateProfile(Boolean updateProfile) {
            this.updateProfile = Optional.ofNullable(updateProfile);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "update_profile", nulls = Nulls.SKIP)
        public _FinalStage updateProfile(Optional<Boolean> updateProfile) {
            this.updateProfile = updateProfile;
            return this;
        }

        @java.lang.Override
        public _FinalStage sendEmail(Boolean sendEmail) {
            this.sendEmail = Optional.ofNullable(sendEmail);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "send_email", nulls = Nulls.SKIP)
        public _FinalStage sendEmail(Optional<Boolean> sendEmail) {
            this.sendEmail = sendEmail;
            return this;
        }

        @java.lang.Override
        public _FinalStage forceCreate(Boolean forceCreate) {
            this.forceCreate = Optional.ofNullable(forceCreate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "force_create", nulls = Nulls.SKIP)
        public _FinalStage forceCreate(Optional<Boolean> forceCreate) {
            this.forceCreate = forceCreate;
            return this;
        }

        @java.lang.Override
        public _FinalStage expirationSeconds(Integer expirationSeconds) {
            this.expirationSeconds = Optional.ofNullable(expirationSeconds);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "expiration_seconds", nulls = Nulls.SKIP)
        public _FinalStage expirationSeconds(Optional<Integer> expirationSeconds) {
            this.expirationSeconds = expirationSeconds;
            return this;
        }

        @java.lang.Override
        public MagicLinkRequest build() {
            return new MagicLinkRequest(
                    email,
                    clientId,
                    redirectUri,
                    expirationSeconds,
                    forceCreate,
                    sendEmail,
                    updateProfile,
                    updatePassword,
                    scope,
                    nonce,
                    codeChallenge,
                    codeChallengeMethod,
                    rememberMe,
                    reusable,
                    additionalProperties);
        }
    }
}
