/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import it.auth.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserProfileAttributeGroupMetadata.Builder.class)
public final class UserProfileAttributeGroupMetadata {
    private final Optional<String> name;

    private final Optional<String> displayHeader;

    private final Optional<String> displayDescription;

    private final Optional<Map<String, Object>> annotations;

    private final Map<String, Object> additionalProperties;

    private UserProfileAttributeGroupMetadata(
            Optional<String> name,
            Optional<String> displayHeader,
            Optional<String> displayDescription,
            Optional<Map<String, Object>> annotations,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.displayHeader = displayHeader;
        this.displayDescription = displayDescription;
        this.annotations = annotations;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("displayHeader")
    public Optional<String> getDisplayHeader() {
        return displayHeader;
    }

    @JsonProperty("displayDescription")
    public Optional<String> getDisplayDescription() {
        return displayDescription;
    }

    @JsonProperty("annotations")
    public Optional<Map<String, Object>> getAnnotations() {
        return annotations;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserProfileAttributeGroupMetadata && equalTo((UserProfileAttributeGroupMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserProfileAttributeGroupMetadata other) {
        return name.equals(other.name)
                && displayHeader.equals(other.displayHeader)
                && displayDescription.equals(other.displayDescription)
                && annotations.equals(other.annotations);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.displayHeader, this.displayDescription, this.annotations);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> displayHeader = Optional.empty();

        private Optional<String> displayDescription = Optional.empty();

        private Optional<Map<String, Object>> annotations = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UserProfileAttributeGroupMetadata other) {
            name(other.getName());
            displayHeader(other.getDisplayHeader());
            displayDescription(other.getDisplayDescription());
            annotations(other.getAnnotations());
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "displayHeader", nulls = Nulls.SKIP)
        public Builder displayHeader(Optional<String> displayHeader) {
            this.displayHeader = displayHeader;
            return this;
        }

        public Builder displayHeader(String displayHeader) {
            this.displayHeader = Optional.ofNullable(displayHeader);
            return this;
        }

        @JsonSetter(value = "displayDescription", nulls = Nulls.SKIP)
        public Builder displayDescription(Optional<String> displayDescription) {
            this.displayDescription = displayDescription;
            return this;
        }

        public Builder displayDescription(String displayDescription) {
            this.displayDescription = Optional.ofNullable(displayDescription);
            return this;
        }

        @JsonSetter(value = "annotations", nulls = Nulls.SKIP)
        public Builder annotations(Optional<Map<String, Object>> annotations) {
            this.annotations = annotations;
            return this;
        }

        public Builder annotations(Map<String, Object> annotations) {
            this.annotations = Optional.ofNullable(annotations);
            return this;
        }

        public UserProfileAttributeGroupMetadata build() {
            return new UserProfileAttributeGroupMetadata(
                    name, displayHeader, displayDescription, annotations, additionalProperties);
        }
    }
}
