/**
 * This file was auto-generated by Fern from our API Definition.
 */
package it.auth.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import it.auth.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserRepresentation.Builder.class)
public final class UserRepresentation {
    private final Optional<List<String>> organizations;

    private final Optional<String> id;

    private final Optional<String> username;

    private final Optional<String> firstName;

    private final Optional<String> lastName;

    private final Optional<String> email;

    private final Optional<Boolean> emailVerified;

    private final Optional<Map<String, List<String>>> attributes;

    private final Optional<UserProfileMetadata> userProfileMetadata;

    private final Optional<Boolean> enabled;

    private final Optional<String> self;

    private final Optional<String> origin;

    private final Optional<Long> createdTimestamp;

    private final Optional<Boolean> totp;

    private final Optional<String> federationLink;

    private final Optional<String> serviceAccountClientId;

    private final Optional<List<CredentialRepresentation>> credentials;

    private final Optional<List<String>> disableableCredentialTypes;

    private final Optional<List<String>> requiredActions;

    private final Optional<List<FederatedIdentityRepresentation>> federatedIdentities;

    private final Optional<List<String>> realmRoles;

    private final Optional<Map<String, List<String>>> clientRoles;

    private final Optional<List<UserConsentRepresentation>> clientConsents;

    private final Optional<Integer> notBefore;

    private final Optional<Map<String, List<String>>> applicationRoles;

    private final Optional<List<SocialLinkRepresentation>> socialLinks;

    private final Optional<List<String>> groups;

    private final Optional<Map<String, Boolean>> access;

    private final Map<String, Object> additionalProperties;

    private UserRepresentation(
            Optional<List<String>> organizations,
            Optional<String> id,
            Optional<String> username,
            Optional<String> firstName,
            Optional<String> lastName,
            Optional<String> email,
            Optional<Boolean> emailVerified,
            Optional<Map<String, List<String>>> attributes,
            Optional<UserProfileMetadata> userProfileMetadata,
            Optional<Boolean> enabled,
            Optional<String> self,
            Optional<String> origin,
            Optional<Long> createdTimestamp,
            Optional<Boolean> totp,
            Optional<String> federationLink,
            Optional<String> serviceAccountClientId,
            Optional<List<CredentialRepresentation>> credentials,
            Optional<List<String>> disableableCredentialTypes,
            Optional<List<String>> requiredActions,
            Optional<List<FederatedIdentityRepresentation>> federatedIdentities,
            Optional<List<String>> realmRoles,
            Optional<Map<String, List<String>>> clientRoles,
            Optional<List<UserConsentRepresentation>> clientConsents,
            Optional<Integer> notBefore,
            Optional<Map<String, List<String>>> applicationRoles,
            Optional<List<SocialLinkRepresentation>> socialLinks,
            Optional<List<String>> groups,
            Optional<Map<String, Boolean>> access,
            Map<String, Object> additionalProperties) {
        this.organizations = organizations;
        this.id = id;
        this.username = username;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.emailVerified = emailVerified;
        this.attributes = attributes;
        this.userProfileMetadata = userProfileMetadata;
        this.enabled = enabled;
        this.self = self;
        this.origin = origin;
        this.createdTimestamp = createdTimestamp;
        this.totp = totp;
        this.federationLink = federationLink;
        this.serviceAccountClientId = serviceAccountClientId;
        this.credentials = credentials;
        this.disableableCredentialTypes = disableableCredentialTypes;
        this.requiredActions = requiredActions;
        this.federatedIdentities = federatedIdentities;
        this.realmRoles = realmRoles;
        this.clientRoles = clientRoles;
        this.clientConsents = clientConsents;
        this.notBefore = notBefore;
        this.applicationRoles = applicationRoles;
        this.socialLinks = socialLinks;
        this.groups = groups;
        this.access = access;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organizations")
    public Optional<List<String>> getOrganizations() {
        return organizations;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        return username;
    }

    @JsonProperty("firstName")
    public Optional<String> getFirstName() {
        return firstName;
    }

    @JsonProperty("lastName")
    public Optional<String> getLastName() {
        return lastName;
    }

    @JsonProperty("email")
    public Optional<String> getEmail() {
        return email;
    }

    @JsonProperty("emailVerified")
    public Optional<Boolean> getEmailVerified() {
        return emailVerified;
    }

    @JsonProperty("attributes")
    public Optional<Map<String, List<String>>> getAttributes() {
        return attributes;
    }

    @JsonProperty("userProfileMetadata")
    public Optional<UserProfileMetadata> getUserProfileMetadata() {
        return userProfileMetadata;
    }

    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    @JsonProperty("self")
    public Optional<String> getSelf() {
        return self;
    }

    @JsonProperty("origin")
    public Optional<String> getOrigin() {
        return origin;
    }

    @JsonProperty("createdTimestamp")
    public Optional<Long> getCreatedTimestamp() {
        return createdTimestamp;
    }

    @JsonProperty("totp")
    public Optional<Boolean> getTotp() {
        return totp;
    }

    @JsonProperty("federationLink")
    public Optional<String> getFederationLink() {
        return federationLink;
    }

    @JsonProperty("serviceAccountClientId")
    public Optional<String> getServiceAccountClientId() {
        return serviceAccountClientId;
    }

    @JsonProperty("credentials")
    public Optional<List<CredentialRepresentation>> getCredentials() {
        return credentials;
    }

    @JsonProperty("disableableCredentialTypes")
    public Optional<List<String>> getDisableableCredentialTypes() {
        return disableableCredentialTypes;
    }

    @JsonProperty("requiredActions")
    public Optional<List<String>> getRequiredActions() {
        return requiredActions;
    }

    @JsonProperty("federatedIdentities")
    public Optional<List<FederatedIdentityRepresentation>> getFederatedIdentities() {
        return federatedIdentities;
    }

    @JsonProperty("realmRoles")
    public Optional<List<String>> getRealmRoles() {
        return realmRoles;
    }

    @JsonProperty("clientRoles")
    public Optional<Map<String, List<String>>> getClientRoles() {
        return clientRoles;
    }

    @JsonProperty("clientConsents")
    public Optional<List<UserConsentRepresentation>> getClientConsents() {
        return clientConsents;
    }

    @JsonProperty("notBefore")
    public Optional<Integer> getNotBefore() {
        return notBefore;
    }

    @JsonProperty("applicationRoles")
    public Optional<Map<String, List<String>>> getApplicationRoles() {
        return applicationRoles;
    }

    @JsonProperty("socialLinks")
    public Optional<List<SocialLinkRepresentation>> getSocialLinks() {
        return socialLinks;
    }

    @JsonProperty("groups")
    public Optional<List<String>> getGroups() {
        return groups;
    }

    @JsonProperty("access")
    public Optional<Map<String, Boolean>> getAccess() {
        return access;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserRepresentation && equalTo((UserRepresentation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserRepresentation other) {
        return organizations.equals(other.organizations)
                && id.equals(other.id)
                && username.equals(other.username)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && email.equals(other.email)
                && emailVerified.equals(other.emailVerified)
                && attributes.equals(other.attributes)
                && userProfileMetadata.equals(other.userProfileMetadata)
                && enabled.equals(other.enabled)
                && self.equals(other.self)
                && origin.equals(other.origin)
                && createdTimestamp.equals(other.createdTimestamp)
                && totp.equals(other.totp)
                && federationLink.equals(other.federationLink)
                && serviceAccountClientId.equals(other.serviceAccountClientId)
                && credentials.equals(other.credentials)
                && disableableCredentialTypes.equals(other.disableableCredentialTypes)
                && requiredActions.equals(other.requiredActions)
                && federatedIdentities.equals(other.federatedIdentities)
                && realmRoles.equals(other.realmRoles)
                && clientRoles.equals(other.clientRoles)
                && clientConsents.equals(other.clientConsents)
                && notBefore.equals(other.notBefore)
                && applicationRoles.equals(other.applicationRoles)
                && socialLinks.equals(other.socialLinks)
                && groups.equals(other.groups)
                && access.equals(other.access);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.organizations,
                this.id,
                this.username,
                this.firstName,
                this.lastName,
                this.email,
                this.emailVerified,
                this.attributes,
                this.userProfileMetadata,
                this.enabled,
                this.self,
                this.origin,
                this.createdTimestamp,
                this.totp,
                this.federationLink,
                this.serviceAccountClientId,
                this.credentials,
                this.disableableCredentialTypes,
                this.requiredActions,
                this.federatedIdentities,
                this.realmRoles,
                this.clientRoles,
                this.clientConsents,
                this.notBefore,
                this.applicationRoles,
                this.socialLinks,
                this.groups,
                this.access);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> organizations = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<String> username = Optional.empty();

        private Optional<String> firstName = Optional.empty();

        private Optional<String> lastName = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<Boolean> emailVerified = Optional.empty();

        private Optional<Map<String, List<String>>> attributes = Optional.empty();

        private Optional<UserProfileMetadata> userProfileMetadata = Optional.empty();

        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> self = Optional.empty();

        private Optional<String> origin = Optional.empty();

        private Optional<Long> createdTimestamp = Optional.empty();

        private Optional<Boolean> totp = Optional.empty();

        private Optional<String> federationLink = Optional.empty();

        private Optional<String> serviceAccountClientId = Optional.empty();

        private Optional<List<CredentialRepresentation>> credentials = Optional.empty();

        private Optional<List<String>> disableableCredentialTypes = Optional.empty();

        private Optional<List<String>> requiredActions = Optional.empty();

        private Optional<List<FederatedIdentityRepresentation>> federatedIdentities = Optional.empty();

        private Optional<List<String>> realmRoles = Optional.empty();

        private Optional<Map<String, List<String>>> clientRoles = Optional.empty();

        private Optional<List<UserConsentRepresentation>> clientConsents = Optional.empty();

        private Optional<Integer> notBefore = Optional.empty();

        private Optional<Map<String, List<String>>> applicationRoles = Optional.empty();

        private Optional<List<SocialLinkRepresentation>> socialLinks = Optional.empty();

        private Optional<List<String>> groups = Optional.empty();

        private Optional<Map<String, Boolean>> access = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UserRepresentation other) {
            organizations(other.getOrganizations());
            id(other.getId());
            username(other.getUsername());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            email(other.getEmail());
            emailVerified(other.getEmailVerified());
            attributes(other.getAttributes());
            userProfileMetadata(other.getUserProfileMetadata());
            enabled(other.getEnabled());
            self(other.getSelf());
            origin(other.getOrigin());
            createdTimestamp(other.getCreatedTimestamp());
            totp(other.getTotp());
            federationLink(other.getFederationLink());
            serviceAccountClientId(other.getServiceAccountClientId());
            credentials(other.getCredentials());
            disableableCredentialTypes(other.getDisableableCredentialTypes());
            requiredActions(other.getRequiredActions());
            federatedIdentities(other.getFederatedIdentities());
            realmRoles(other.getRealmRoles());
            clientRoles(other.getClientRoles());
            clientConsents(other.getClientConsents());
            notBefore(other.getNotBefore());
            applicationRoles(other.getApplicationRoles());
            socialLinks(other.getSocialLinks());
            groups(other.getGroups());
            access(other.getAccess());
            return this;
        }

        @JsonSetter(value = "organizations", nulls = Nulls.SKIP)
        public Builder organizations(Optional<List<String>> organizations) {
            this.organizations = organizations;
            return this;
        }

        public Builder organizations(List<String> organizations) {
            this.organizations = Optional.ofNullable(organizations);
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public Builder username(Optional<String> username) {
            this.username = username;
            return this;
        }

        public Builder username(String username) {
            this.username = Optional.ofNullable(username);
            return this;
        }

        @JsonSetter(value = "firstName", nulls = Nulls.SKIP)
        public Builder firstName(Optional<String> firstName) {
            this.firstName = firstName;
            return this;
        }

        public Builder firstName(String firstName) {
            this.firstName = Optional.ofNullable(firstName);
            return this;
        }

        @JsonSetter(value = "lastName", nulls = Nulls.SKIP)
        public Builder lastName(Optional<String> lastName) {
            this.lastName = lastName;
            return this;
        }

        public Builder lastName(String lastName) {
            this.lastName = Optional.ofNullable(lastName);
            return this;
        }

        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<String> email) {
            this.email = email;
            return this;
        }

        public Builder email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        @JsonSetter(value = "emailVerified", nulls = Nulls.SKIP)
        public Builder emailVerified(Optional<Boolean> emailVerified) {
            this.emailVerified = emailVerified;
            return this;
        }

        public Builder emailVerified(Boolean emailVerified) {
            this.emailVerified = Optional.ofNullable(emailVerified);
            return this;
        }

        @JsonSetter(value = "attributes", nulls = Nulls.SKIP)
        public Builder attributes(Optional<Map<String, List<String>>> attributes) {
            this.attributes = attributes;
            return this;
        }

        public Builder attributes(Map<String, List<String>> attributes) {
            this.attributes = Optional.ofNullable(attributes);
            return this;
        }

        @JsonSetter(value = "userProfileMetadata", nulls = Nulls.SKIP)
        public Builder userProfileMetadata(Optional<UserProfileMetadata> userProfileMetadata) {
            this.userProfileMetadata = userProfileMetadata;
            return this;
        }

        public Builder userProfileMetadata(UserProfileMetadata userProfileMetadata) {
            this.userProfileMetadata = Optional.ofNullable(userProfileMetadata);
            return this;
        }

        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        @JsonSetter(value = "self", nulls = Nulls.SKIP)
        public Builder self(Optional<String> self) {
            this.self = self;
            return this;
        }

        public Builder self(String self) {
            this.self = Optional.ofNullable(self);
            return this;
        }

        @JsonSetter(value = "origin", nulls = Nulls.SKIP)
        public Builder origin(Optional<String> origin) {
            this.origin = origin;
            return this;
        }

        public Builder origin(String origin) {
            this.origin = Optional.ofNullable(origin);
            return this;
        }

        @JsonSetter(value = "createdTimestamp", nulls = Nulls.SKIP)
        public Builder createdTimestamp(Optional<Long> createdTimestamp) {
            this.createdTimestamp = createdTimestamp;
            return this;
        }

        public Builder createdTimestamp(Long createdTimestamp) {
            this.createdTimestamp = Optional.ofNullable(createdTimestamp);
            return this;
        }

        @JsonSetter(value = "totp", nulls = Nulls.SKIP)
        public Builder totp(Optional<Boolean> totp) {
            this.totp = totp;
            return this;
        }

        public Builder totp(Boolean totp) {
            this.totp = Optional.ofNullable(totp);
            return this;
        }

        @JsonSetter(value = "federationLink", nulls = Nulls.SKIP)
        public Builder federationLink(Optional<String> federationLink) {
            this.federationLink = federationLink;
            return this;
        }

        public Builder federationLink(String federationLink) {
            this.federationLink = Optional.ofNullable(federationLink);
            return this;
        }

        @JsonSetter(value = "serviceAccountClientId", nulls = Nulls.SKIP)
        public Builder serviceAccountClientId(Optional<String> serviceAccountClientId) {
            this.serviceAccountClientId = serviceAccountClientId;
            return this;
        }

        public Builder serviceAccountClientId(String serviceAccountClientId) {
            this.serviceAccountClientId = Optional.ofNullable(serviceAccountClientId);
            return this;
        }

        @JsonSetter(value = "credentials", nulls = Nulls.SKIP)
        public Builder credentials(Optional<List<CredentialRepresentation>> credentials) {
            this.credentials = credentials;
            return this;
        }

        public Builder credentials(List<CredentialRepresentation> credentials) {
            this.credentials = Optional.ofNullable(credentials);
            return this;
        }

        @JsonSetter(value = "disableableCredentialTypes", nulls = Nulls.SKIP)
        public Builder disableableCredentialTypes(Optional<List<String>> disableableCredentialTypes) {
            this.disableableCredentialTypes = disableableCredentialTypes;
            return this;
        }

        public Builder disableableCredentialTypes(List<String> disableableCredentialTypes) {
            this.disableableCredentialTypes = Optional.ofNullable(disableableCredentialTypes);
            return this;
        }

        @JsonSetter(value = "requiredActions", nulls = Nulls.SKIP)
        public Builder requiredActions(Optional<List<String>> requiredActions) {
            this.requiredActions = requiredActions;
            return this;
        }

        public Builder requiredActions(List<String> requiredActions) {
            this.requiredActions = Optional.ofNullable(requiredActions);
            return this;
        }

        @JsonSetter(value = "federatedIdentities", nulls = Nulls.SKIP)
        public Builder federatedIdentities(Optional<List<FederatedIdentityRepresentation>> federatedIdentities) {
            this.federatedIdentities = federatedIdentities;
            return this;
        }

        public Builder federatedIdentities(List<FederatedIdentityRepresentation> federatedIdentities) {
            this.federatedIdentities = Optional.ofNullable(federatedIdentities);
            return this;
        }

        @JsonSetter(value = "realmRoles", nulls = Nulls.SKIP)
        public Builder realmRoles(Optional<List<String>> realmRoles) {
            this.realmRoles = realmRoles;
            return this;
        }

        public Builder realmRoles(List<String> realmRoles) {
            this.realmRoles = Optional.ofNullable(realmRoles);
            return this;
        }

        @JsonSetter(value = "clientRoles", nulls = Nulls.SKIP)
        public Builder clientRoles(Optional<Map<String, List<String>>> clientRoles) {
            this.clientRoles = clientRoles;
            return this;
        }

        public Builder clientRoles(Map<String, List<String>> clientRoles) {
            this.clientRoles = Optional.ofNullable(clientRoles);
            return this;
        }

        @JsonSetter(value = "clientConsents", nulls = Nulls.SKIP)
        public Builder clientConsents(Optional<List<UserConsentRepresentation>> clientConsents) {
            this.clientConsents = clientConsents;
            return this;
        }

        public Builder clientConsents(List<UserConsentRepresentation> clientConsents) {
            this.clientConsents = Optional.ofNullable(clientConsents);
            return this;
        }

        @JsonSetter(value = "notBefore", nulls = Nulls.SKIP)
        public Builder notBefore(Optional<Integer> notBefore) {
            this.notBefore = notBefore;
            return this;
        }

        public Builder notBefore(Integer notBefore) {
            this.notBefore = Optional.ofNullable(notBefore);
            return this;
        }

        @JsonSetter(value = "applicationRoles", nulls = Nulls.SKIP)
        public Builder applicationRoles(Optional<Map<String, List<String>>> applicationRoles) {
            this.applicationRoles = applicationRoles;
            return this;
        }

        public Builder applicationRoles(Map<String, List<String>> applicationRoles) {
            this.applicationRoles = Optional.ofNullable(applicationRoles);
            return this;
        }

        @JsonSetter(value = "socialLinks", nulls = Nulls.SKIP)
        public Builder socialLinks(Optional<List<SocialLinkRepresentation>> socialLinks) {
            this.socialLinks = socialLinks;
            return this;
        }

        public Builder socialLinks(List<SocialLinkRepresentation> socialLinks) {
            this.socialLinks = Optional.ofNullable(socialLinks);
            return this;
        }

        @JsonSetter(value = "groups", nulls = Nulls.SKIP)
        public Builder groups(Optional<List<String>> groups) {
            this.groups = groups;
            return this;
        }

        public Builder groups(List<String> groups) {
            this.groups = Optional.ofNullable(groups);
            return this;
        }

        @JsonSetter(value = "access", nulls = Nulls.SKIP)
        public Builder access(Optional<Map<String, Boolean>> access) {
            this.access = access;
            return this;
        }

        public Builder access(Map<String, Boolean> access) {
            this.access = Optional.ofNullable(access);
            return this;
        }

        public UserRepresentation build() {
            return new UserRepresentation(
                    organizations,
                    id,
                    username,
                    firstName,
                    lastName,
                    email,
                    emailVerified,
                    attributes,
                    userProfileMetadata,
                    enabled,
                    self,
                    origin,
                    createdTimestamp,
                    totp,
                    federationLink,
                    serviceAccountClientId,
                    credentials,
                    disableableCredentialTypes,
                    requiredActions,
                    federatedIdentities,
                    realmRoles,
                    clientRoles,
                    clientConsents,
                    notBefore,
                    applicationRoles,
                    socialLinks,
                    groups,
                    access,
                    additionalProperties);
        }
    }
}
