/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo;

import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.types.AdminEventRepresentation;
import com.phasetwo.types.AuditEventRepresentation;
import com.phasetwo.types.EventRepresentation;
import com.phasetwo.types.GetAdminRealmsRealmExtAdminEventsAdminEventsRequest;
import com.phasetwo.types.GetAdminRealmsRealmExtAdminEventsEventsRequest;
import com.phasetwo.types.GetWebhooksRequest;
import com.phasetwo.types.WebhookRepresentation;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncEventsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEventsClient rawClient;

    public AsyncEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEventsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<Void> deleteAllAdminEvents(String realm) {
        return this.rawClient.deleteAllAdminEvents(realm).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> deleteAllAdminEvents(String realm, RequestOptions requestOptions) {
        return this.rawClient.deleteAllAdminEvents(realm, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> deleteAllEvents(String realm) {
        return this.rawClient.deleteAllEvents(realm).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> deleteAllEvents(String realm, RequestOptions requestOptions) {
        return this.rawClient.deleteAllEvents(realm, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(String realm) {
        return this.rawClient.createEvent(realm).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(String realm, AuditEventRepresentation request) {
        return this.rawClient.createEvent(realm, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createEvent(
            String realm, AuditEventRepresentation request, RequestOptions requestOptions) {
        return this.rawClient.createEvent(realm, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get a list of webhooks for this realm
     */
    public CompletableFuture<List<WebhookRepresentation>> getWebhooks(String realm) {
        return this.rawClient.getWebhooks(realm).thenApply(response -> response.body());
    }

    /**
     * Get a list of webhooks for this realm
     */
    public CompletableFuture<List<WebhookRepresentation>> getWebhooks(String realm, GetWebhooksRequest request) {
        return this.rawClient.getWebhooks(realm, request).thenApply(response -> response.body());
    }

    /**
     * Get a list of webhooks for this realm
     */
    public CompletableFuture<List<WebhookRepresentation>> getWebhooks(
            String realm, GetWebhooksRequest request, RequestOptions requestOptions) {
        return this.rawClient.getWebhooks(realm, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createWebhook(String realm) {
        return this.rawClient.createWebhook(realm).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createWebhook(String realm, WebhookRepresentation request) {
        return this.rawClient.createWebhook(realm, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> createWebhook(
            String realm, WebhookRepresentation request, RequestOptions requestOptions) {
        return this.rawClient.createWebhook(realm, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get a count of webhooks.
     */
    public CompletableFuture<Integer> getWebhooksCount(String realm) {
        return this.rawClient.getWebhooksCount(realm).thenApply(response -> response.body());
    }

    /**
     * Get a count of webhooks.
     */
    public CompletableFuture<Integer> getWebhooksCount(String realm, RequestOptions requestOptions) {
        return this.rawClient.getWebhooksCount(realm, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<WebhookRepresentation> getWebhookById(String realm, String webhookId) {
        return this.rawClient.getWebhookById(realm, webhookId).thenApply(response -> response.body());
    }

    public CompletableFuture<WebhookRepresentation> getWebhookById(
            String realm, String webhookId, RequestOptions requestOptions) {
        return this.rawClient.getWebhookById(realm, webhookId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> updateWebhook(String realm, String webhookId) {
        return this.rawClient.updateWebhook(realm, webhookId).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> updateWebhook(String realm, String webhookId, WebhookRepresentation request) {
        return this.rawClient.updateWebhook(realm, webhookId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> updateWebhook(
            String realm, String webhookId, WebhookRepresentation request, RequestOptions requestOptions) {
        return this.rawClient
                .updateWebhook(realm, webhookId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<Void> deleteWebhook(String realm, String webhookId) {
        return this.rawClient.deleteWebhook(realm, webhookId).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> deleteWebhook(String realm, String webhookId, RequestOptions requestOptions) {
        return this.rawClient.deleteWebhook(realm, webhookId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<List<EventRepresentation>>
            getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(String realm) {
        return this.rawClient
                .getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(realm)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<EventRepresentation>>
            getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(
                    String realm, GetAdminRealmsRealmExtAdminEventsEventsRequest request) {
        return this.rawClient
                .getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(realm, request)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<EventRepresentation>>
            getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(
                    String realm,
                    GetAdminRealmsRealmExtAdminEventsEventsRequest request,
                    RequestOptions requestOptions) {
        return this.rawClient
                .getEventsReturnsAllEventsOrFiltersThemBasedOnUrlQueryParametersListedHere(
                        realm, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<AdminEventRepresentation>>
            getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(String realm) {
        return this.rawClient
                .getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(realm)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<AdminEventRepresentation>>
            getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(
                    String realm, GetAdminRealmsRealmExtAdminEventsAdminEventsRequest request) {
        return this.rawClient
                .getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(realm, request)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<List<AdminEventRepresentation>>
            getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(
                    String realm,
                    GetAdminRealmsRealmExtAdminEventsAdminEventsRequest request,
                    RequestOptions requestOptions) {
        return this.rawClient
                .getAdminEventsReturnsAllAdminEventsOrFiltersEventsBasedOnUrlQueryParametersListedHere(
                        realm, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
