/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.MediaTypes;
import com.phasetwo.core.ObjectMappers;
import com.phasetwo.core.PhasetwoApiException;
import com.phasetwo.core.PhasetwoClientHttpResponse;
import com.phasetwo.core.PhasetwoException;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.types.IdentityProviderMapperRepresentation;
import com.phasetwo.types.IdentityProviderRepresentation;
import com.phasetwo.types.LinkIdentityProviderRepresentation;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawIdentityProvidersClient {
    protected final ClientOptions clientOptions;

    public RawIdentityProvidersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public PhasetwoClientHttpResponse<Map<String, Object>> importIdpJson(String realm, String orgId) {
        return importIdpJson(realm, orgId, null);
    }

    public PhasetwoClientHttpResponse<Map<String, Object>> importIdpJson(
            String realm, String orgId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps/import-config")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<Map<String, Object>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<List<IdentityProviderRepresentation>> getIdps(String realm, String orgId) {
        return getIdps(realm, orgId, null);
    }

    public PhasetwoClientHttpResponse<List<IdentityProviderRepresentation>> getIdps(
            String realm, String orgId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<List<IdentityProviderRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> createIdp(String realm, String orgId) {
        return createIdp(realm, orgId, IdentityProviderRepresentation.builder().build());
    }

    public PhasetwoClientHttpResponse<Void> createIdp(
            String realm, String orgId, IdentityProviderRepresentation request) {
        return createIdp(realm, orgId, request, null);
    }

    public PhasetwoClientHttpResponse<Void> createIdp(
            String realm, String orgId, IdentityProviderRepresentation request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhasetwoException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> linkIdp(String realm, String orgId) {
        return linkIdp(
                realm, orgId, LinkIdentityProviderRepresentation.builder().build());
    }

    public PhasetwoClientHttpResponse<Void> linkIdp(
            String realm, String orgId, LinkIdentityProviderRepresentation request) {
        return linkIdp(realm, orgId, request, null);
    }

    public PhasetwoClientHttpResponse<Void> linkIdp(
            String realm, String orgId, LinkIdentityProviderRepresentation request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps/link")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhasetwoException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> unlinkIdp(String realm, String orgId, String alias) {
        return unlinkIdp(realm, orgId, alias, null);
    }

    public PhasetwoClientHttpResponse<Void> unlinkIdp(
            String realm, String orgId, String alias, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("unlink")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<IdentityProviderRepresentation> getIdp(String realm, String orgId, String alias) {
        return getIdp(realm, orgId, alias, null);
    }

    public PhasetwoClientHttpResponse<IdentityProviderRepresentation> getIdp(
            String realm, String orgId, String alias, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), IdentityProviderRepresentation.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> updateIdp(String realm, String orgId, String alias) {
        return updateIdp(
                realm, orgId, alias, IdentityProviderRepresentation.builder().build());
    }

    public PhasetwoClientHttpResponse<Void> updateIdp(
            String realm, String orgId, String alias, IdentityProviderRepresentation request) {
        return updateIdp(realm, orgId, alias, request, null);
    }

    public PhasetwoClientHttpResponse<Void> updateIdp(
            String realm,
            String orgId,
            String alias,
            IdentityProviderRepresentation request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhasetwoException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> deleteIdp(String realm, String orgId, String alias) {
        return deleteIdp(realm, orgId, alias, null);
    }

    public PhasetwoClientHttpResponse<Void> deleteIdp(
            String realm, String orgId, String alias, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<List<IdentityProviderMapperRepresentation>> getIdpMappers(
            String realm, String orgId, String alias) {
        return getIdpMappers(realm, orgId, alias, null);
    }

    public PhasetwoClientHttpResponse<List<IdentityProviderMapperRepresentation>> getIdpMappers(
            String realm, String orgId, String alias, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("mappers")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(),
                                new TypeReference<List<IdentityProviderMapperRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> addIdpMapper(String realm, String orgId, String alias) {
        return addIdpMapper(
                realm,
                orgId,
                alias,
                IdentityProviderMapperRepresentation.builder().build());
    }

    public PhasetwoClientHttpResponse<Void> addIdpMapper(
            String realm, String orgId, String alias, IdentityProviderMapperRepresentation request) {
        return addIdpMapper(realm, orgId, alias, request, null);
    }

    public PhasetwoClientHttpResponse<Void> addIdpMapper(
            String realm,
            String orgId,
            String alias,
            IdentityProviderMapperRepresentation request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("mappers")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhasetwoException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<IdentityProviderMapperRepresentation> getIdpMapper(
            String realm, String orgId, String alias, String id) {
        return getIdpMapper(realm, orgId, alias, id, null);
    }

    public PhasetwoClientHttpResponse<IdentityProviderMapperRepresentation> getIdpMapper(
            String realm, String orgId, String alias, String id, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("mappers")
                .addPathSegment(id)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), IdentityProviderMapperRepresentation.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> updateIdpMapper(String realm, String orgId, String alias, String id) {
        return updateIdpMapper(
                realm,
                orgId,
                alias,
                id,
                IdentityProviderMapperRepresentation.builder().build());
    }

    public PhasetwoClientHttpResponse<Void> updateIdpMapper(
            String realm, String orgId, String alias, String id, IdentityProviderMapperRepresentation request) {
        return updateIdpMapper(realm, orgId, alias, id, request, null);
    }

    public PhasetwoClientHttpResponse<Void> updateIdpMapper(
            String realm,
            String orgId,
            String alias,
            String id,
            IdentityProviderMapperRepresentation request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("mappers")
                .addPathSegment(id)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhasetwoException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<Void> deleteIdpMapper(String realm, String orgId, String alias, String id) {
        return deleteIdpMapper(realm, orgId, alias, id, null);
    }

    public PhasetwoClientHttpResponse<Void> deleteIdpMapper(
            String realm, String orgId, String alias, String id, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("idps")
                .addPathSegment(alias)
                .addPathSegments("mappers")
                .addPathSegment(id)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }
}
