/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo;

import com.fasterxml.jackson.core.type.TypeReference;
import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.ObjectMappers;
import com.phasetwo.core.PhasetwoApiException;
import com.phasetwo.core.PhasetwoClientHttpResponse;
import com.phasetwo.core.PhasetwoException;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.types.OrganizationDomainRepresentation;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawOrganizationClient {
    protected final ClientOptions clientOptions;

    public RawOrganizationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public PhasetwoClientHttpResponse<List<OrganizationDomainRepresentation>> getOrganizationDomains(
            String realm, String orgId) {
        return getOrganizationDomains(realm, orgId, null);
    }

    public PhasetwoClientHttpResponse<List<OrganizationDomainRepresentation>> getOrganizationDomains(
            String realm, String orgId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("domains")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), new TypeReference<List<OrganizationDomainRepresentation>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    public PhasetwoClientHttpResponse<OrganizationDomainRepresentation> getOrganizationDomain(
            String realm, String orgId, String domainName) {
        return getOrganizationDomain(realm, orgId, domainName, null);
    }

    public PhasetwoClientHttpResponse<OrganizationDomainRepresentation> getOrganizationDomain(
            String realm, String orgId, String domainName, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("realms")
                .addPathSegment(realm)
                .addPathSegments("orgs")
                .addPathSegment(orgId)
                .addPathSegments("domains")
                .addPathSegment(domainName)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBody.string(), OrganizationDomainRepresentation.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }
}
