/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phasetwo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.phasetwo.core.ClientOptions;
import com.phasetwo.core.ObjectMappers;
import com.phasetwo.core.PhasetwoApiException;
import com.phasetwo.core.PhasetwoClientHttpResponse;
import com.phasetwo.core.PhasetwoException;
import com.phasetwo.core.QueryStringMapper;
import com.phasetwo.core.RequestOptions;
import com.phasetwo.errors.ForbiddenError;
import com.phasetwo.errors.NotFoundError;
import com.phasetwo.types.DeleteAdminRealmsRealmSessionsSessionRequest;
import com.phasetwo.types.GlobalRequestResult;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawSessionsClient {
    protected final ClientOptions clientOptions;

    public RawSessionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Any client that has an admin url will also be told to invalidate any sessions they have.
     */
    public PhasetwoClientHttpResponse<GlobalRequestResult> removesAllUserSessions(String realm) {
        return removesAllUserSessions(realm, null);
    }

    /**
     * Any client that has an admin url will also be told to invalidate any sessions they have.
     */
    public PhasetwoClientHttpResponse<GlobalRequestResult> removesAllUserSessions(
            String realm, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("logout-all")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GlobalRequestResult.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                if (response.code() == 403) {
                    throw new ForbiddenError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }

    /**
     * Any client that has an admin url will also be told to invalidate this particular session.
     */
    public PhasetwoClientHttpResponse<Void> removeASpecificUserSession(String realm, String session) {
        return removeASpecificUserSession(
                realm,
                session,
                DeleteAdminRealmsRealmSessionsSessionRequest.builder().build());
    }

    /**
     * Any client that has an admin url will also be told to invalidate this particular session.
     */
    public PhasetwoClientHttpResponse<Void> removeASpecificUserSession(
            String realm, String session, DeleteAdminRealmsRealmSessionsSessionRequest request) {
        return removeASpecificUserSession(realm, session, request, null);
    }

    /**
     * Any client that has an admin url will also be told to invalidate this particular session.
     */
    public PhasetwoClientHttpResponse<Void> removeASpecificUserSession(
            String realm,
            String session,
            DeleteAdminRealmsRealmSessionsSessionRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("admin/realms")
                .addPathSegment(realm)
                .addPathSegments("sessions")
                .addPathSegment(session);
        if (request.getIsOffline().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "isOffline", request.getIsOffline().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PhasetwoClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PhasetwoApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PhasetwoException("Network error executing HTTP request", e);
        }
    }
}
